---
title: "05_access_scenarios"
output: html_document
---

This notebook projects scenarios of charging demand and analyses household access for each scenario and according to different housing types.

```{r}
library(tidyverse)
library(reshape2)
library(ggplot2)
library(stringr)
library(colorspace)
library(cowplot)
```

```{r}
setwd('C:/Users/Louis Rosset/Documents/EPFL/Master Project/Grid_limits_EV_charging/04_allocation/IOUdata')
SCEtypes = read.csv("SCE/circuitfiles/SCE_ICAalldemoallocclasses.csv", header=T, na.strings="?")
SCE_ICAaccess = read.csv("SCE/circuitfiles/SCE_ICAalldemoalloc.csv", header=T, na.strings="?", colClasses=as.character(SCEtypes$x))

PGEtypes = read.csv("PGE/circuitfiles/PGE_ICAalldemoallocclasses.csv", header=T, na.strings="?")
PGE_ICAaccess = read.csv("PGE/circuitfiles/PGE_ICAalldemoalloc.csv", header=T, na.strings="?", colClasses=as.character(PGEtypes$x))

# at <- c("1", "1.5", "2.0", "3.0", "4.0", "4.5", "5.0", "6.0", "7.0", "8.0", "9.0", "10.")

###EXTRA FEATURES FOR HOUSING###
SCEhousingtypes <- read.csv("SCE/circuitfiles/SCE_ICAalldemo_housing_classes.csv", header = TRUE, na.strings = "?")
SCE_ICA_housing <- read.csv("SCE/circuitfiles/SCE_ICAalldemoalloc_housing.csv", header = TRUE, na.strings = "?", colClasses = as.character(SCEhousingtypes$x))

PGEhousingtypes <- read.csv("PGE/circuitfiles/PGE_ICAalldemo_housing_classes.csv", header = TRUE, na.strings = "?")
PGE_ICA_housing <- read.csv("PGE/circuitfiles/PGE_ICAalldemoalloc_housing.csv", header = TRUE, na.strings = "?", colClasses = as.character(PGEhousingtypes$x))

#Correcting some duplicates problem
PGE_ICAaccess <- PGE_ICAaccess[!duplicated(PGE_ICAaccess[, c("GEOID", "CircuitName")]), ]
PGE_ICA_housing <- PGE_ICA_housing[!duplicated(PGE_ICA_housing[, c("GEOID", "CircuitName")]), ]

SCE_ICAaccess <- merge(SCE_ICAaccess, SCE_ICA_housing[, c("GEOID", "CircuitName", "tothh_Cpoly", "tothh_SU_Cpoly", "tothh_duplex_Cpoly", "tothh_3to4_Cpoly", "tothh_5to9_Cpoly", "tothh_10to19_Cpoly", "tothh_20to49_Cpoly", "tothh_50plus_Cpoly")], by = c("GEOID", "CircuitName", "tothh_Cpoly"))

PGE_ICAaccess <- merge(PGE_ICAaccess, PGE_ICA_housing[, c("GEOID", "CircuitName", "tothh_Cpoly", "tothh_SU_Cpoly", "tothh_duplex_Cpoly", "tothh_3to4_Cpoly", "tothh_5to9_Cpoly", "tothh_10to19_Cpoly", "tothh_20to49_Cpoly", "tothh_50plus_Cpoly")], by = c("GEOID", "CircuitName", "tothh_Cpoly"))

rm(PGE_ICA_housing, SCE_ICA_housing, PGEhousingtypes, SCEhousingtypes, PGEtypes, SCEtypes)
### ------------------------###
```

Importing vehicle's ownership data
```{r}
# Estimated average number of vehicles per household in 2017-2021, at Census Block Group level (Source: ACS 5-years average - found on https://ucberkeley.policymap.com/)
setwd('C:/Users/Louis Rosset/Documents/EPFL/Master Project/Grid_limits_EV_charging/01_demodata')
ACS_bg_vehicles_hh = read.csv("Average_number_of_vehicles_per_household.csv", header = TRUE, skip = 1, na.strings = "?")
ACS_bg_vehicles_hh <- ACS_bg_vehicles_hh %>%
  select(GEOID = GeoID_Name, avgveh_hh = avmv) %>%
  mutate(GEOID = as.character(GEOID),
         avgveh_hh = as.numeric(avgveh_hh))
```

```{r}
#We calculate the amount of households without access per capacity threshold
plotops_csgrid = list(
  theme_light(), facet_grid(IOU~scenario, scales="free_x", space='free_x'),
  geom_boxplot(aes(), alpha=1, width=0.9),
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), legend.position="none"),
  scale_y_continuous(breaks = seq(0, 7, by = 1)),
  labs(x=element_blank(), y="Average deficit of capacity (kW/hh), by circuit segment"),
  scale_fill_manual(values = c("1 - Indiv. access (1.5kW)" = "#7EE081", 
                               "2 - Indiv. access (7kW)" = "#62A87C", 
                               "3 - Shared access" = "#00487C", 
                               "4 - Mixed" = "#F6F5AE"))
)
```

```{r}
#Preparing data 
LVL1_CHRG_PWR <- 1.5 #level 1 power
LVL2_CHRG_PWR <- 7.0 #level 2 power
NUM_VEH_CHRG <- 6.5   #from 6 to 7 vehicles per charging station, from Executive Orders B4818 and N7920.

IOU_wacc <- rbind(select(PGE_ICAaccess, GEOID, county, IOU, tothh_Cpoly, tothh_SU_Cpoly, tothh_duplex_Cpoly, tothh_3to4_Cpoly, tothh_5to9_Cpoly, tothh_10to19_Cpoly, tothh_20to49_Cpoly, tothh_50plus_Cpoly, ICL_kWphh, ICL_max_hhWt_nadj),
        select(SCE_ICAaccess, GEOID, county, IOU, tothh_Cpoly, tothh_SU_Cpoly, tothh_duplex_Cpoly, tothh_3to4_Cpoly, tothh_5to9_Cpoly, tothh_10to19_Cpoly, tothh_20to49_Cpoly, tothh_50plus_Cpoly, ICL_kWphh, ICL_max_hhWt_nadj)) %>%
  mutate(ICL_max_hhWt_nadj = if_else(IOU == "SCE", ICL_max_hhWt_nadj * 1000, ICL_max_hhWt_nadj)) %>%
  mutate(tothh_small_Cpoly = tothh_3to4_Cpoly + tothh_5to9_Cpoly + tothh_10to19_Cpoly) %>%
  mutate(tothh_large_Cpoly = tothh_20to49_Cpoly + tothh_50plus_Cpoly) %>%
  mutate(tothh_MUD_Cpoly = tothh_duplex_Cpoly + tothh_small_Cpoly + tothh_large_Cpoly)  

IOU_wacc <- merge(IOU_wacc, ACS_bg_vehicles_hh[, c("GEOID", "avgveh_hh")], 
                     by = "GEOID", all.x = TRUE) %>%
  mutate(totveh_Cpoly = tothh_Cpoly*avgveh_hh) %>%
  mutate(totveh_SU_Cpoly = tothh_SU_Cpoly*avgveh_hh) %>%
  mutate(totveh_duplex_Cpoly = tothh_duplex_Cpoly*avgveh_hh) %>%
  mutate(totveh_small_Cpoly = tothh_small_Cpoly*avgveh_hh) %>%
  mutate(totveh_large_Cpoly = tothh_large_Cpoly*avgveh_hh) %>%
  mutate(totveh_MUD_Cpoly = tothh_MUD_Cpoly*avgveh_hh) %>%
  mutate(ICL_kWpveh = ICL_kWphh/avgveh_hh)
```

```{r}
 #SCENARIO 1
 #Individual charging
 #All households should have access to his individual level 1 (1.5kW) charging infrastructure.
 IOU_wacc_sc1 <- IOU_wacc %>%
 mutate(sc1_veh_load = tothh_Cpoly*LVL1_CHRG_PWR)%>%
  mutate(sc1_veh_headroom = ICL_max_hhWt_nadj - sc1_veh_load) %>%
  mutate(sc1_vehwacc = ifelse(sc1_veh_headroom>=0, totveh_Cpoly, totveh_Cpoly*ICL_max_hhWt_nadj/sc1_veh_load))%>%
  mutate(sc1_hhwacc = ifelse(sc1_veh_headroom>=0, tothh_Cpoly, tothh_Cpoly*ICL_max_hhWt_nadj/sc1_veh_load)) %>%
  mutate(ICL_hhnoacc = -ifelse(sc1_veh_headroom<0, sc1_veh_headroom/tothh_Cpoly, 0)) %>%
  mutate(sc1_vehwacc_pct = sc1_vehwacc/totveh_Cpoly)%>%
  mutate(sc1_hhwacc_pct = sc1_hhwacc/tothh_Cpoly)%>%
  #vehicles with access
  mutate(sc1_vehwacc_SU = sc1_vehwacc_pct*totveh_SU_Cpoly)%>%
  mutate(sc1_vehwacc_duplex = sc1_vehwacc_pct*totveh_duplex_Cpoly)%>%
  mutate(sc1_vehwacc_small = sc1_vehwacc_pct*totveh_small_Cpoly)%>%
  mutate(sc1_vehwacc_large = sc1_vehwacc_pct*totveh_large_Cpoly)%>%
  mutate(sc1_vehwacc_MUD = sc1_vehwacc_pct*totveh_MUD_Cpoly)%>%
  #for all type of housing
  #households with access
  mutate(sc1_hhwacc_SU = sc1_hhwacc_pct*tothh_SU_Cpoly)%>%
  mutate(sc1_hhwacc_duplex = sc1_hhwacc_pct*tothh_duplex_Cpoly)%>%
  mutate(sc1_hhwacc_small = sc1_hhwacc_pct*tothh_small_Cpoly)%>%
  mutate(sc1_hhwacc_large = sc1_hhwacc_pct*tothh_large_Cpoly)%>%
  mutate(sc1_hhwacc_MUD = sc1_hhwacc_pct*tothh_MUD_Cpoly)%>%
  mutate(scenario = "sc1")

cat(" Scenario 1 - All households should have access to an individual level 1 (1.5 kW) charging facility.

    All: We estimate that ",sum(IOU_wacc_sc1$sc1_vehwacc, na.rm = TRUE)," vehicles and ",sum(IOU_wacc_sc1$sc1_hhwacc, na.rm = TRUE)," households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc1$sc1_vehwacc, na.rm = TRUE)/sum(IOU_wacc_sc1$totveh_Cpoly, na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc1$sc1_hhwacc, na.rm = TRUE)/sum(IOU_wacc_sc1$tothh_Cpoly, na.rm = TRUE)*100), "% of all households in PG&E and SCE service territory.
    
    PG&E: We estimate that ", sum(IOU_wacc_sc1$sc1_vehwacc[IOU_wacc_sc1$IOU == "PGE"], na.rm = TRUE), "vehicles and ", sum(IOU_wacc_sc1$sc1_hhwacc[IOU_wacc_sc1$IOU == "PGE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc1$sc1_vehwacc[IOU_wacc_sc1$IOU == "PGE"], na.rm = TRUE)/sum(IOU_wacc_sc1$totveh_Cpoly[IOU_wacc_sc1$IOU == "PGE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc1$sc1_hhwacc[IOU_wacc_sc1$IOU == "PGE"], na.rm = TRUE)/sum(IOU_wacc_sc1$tothh_Cpoly[IOU_wacc_sc1$IOU == "PGE"], na.rm = TRUE)*100), "% of all households in PG&E territory.

    SCE: We estimate that ", sum(IOU_wacc_sc1$sc1_vehwacc[IOU_wacc_sc1$IOU == "SCE"], na.rm = TRUE), "vehicles and ", sum(IOU_wacc_sc1$sc1_hhwacc[IOU_wacc_sc1$IOU == "SCE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc1$sc1_vehwacc[IOU_wacc_sc1$IOU == "SCE"], na.rm = TRUE)/sum(IOU_wacc_sc1$totveh_Cpoly[IOU_wacc_sc1$IOU == "SCE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc1$sc1_hhwacc[IOU_wacc_sc1$IOU == "SCE"], na.rm = TRUE)/sum(IOU_wacc_sc1$tothh_Cpoly[IOU_wacc_sc1$IOU == "SCE"], na.rm = TRUE)*100), "% of all households in SCE territory.")
```

```{r}
 #SCENARIO 2
 #Individual charging
 #All households should have access to his individual level 2 (7.0kW) charging infrastructure.
 IOU_wacc_sc2 <- IOU_wacc %>%
 mutate(sc2_veh_load = tothh_Cpoly*LVL2_CHRG_PWR)%>%
  mutate(sc2_veh_headroom = ICL_max_hhWt_nadj - sc2_veh_load) %>%
  mutate(sc2_vehwacc = ifelse(sc2_veh_headroom>=0, totveh_Cpoly, totveh_Cpoly*ICL_max_hhWt_nadj/sc2_veh_load))%>%
  mutate(sc2_hhwacc = ifelse(sc2_veh_headroom>=0, tothh_Cpoly, tothh_Cpoly*ICL_max_hhWt_nadj/sc2_veh_load)) %>%
  mutate(ICL_hhnoacc = -ifelse(sc2_veh_headroom<0, sc2_veh_headroom/tothh_Cpoly, 0)) %>%
  mutate(sc2_vehwacc_pct = sc2_vehwacc/totveh_Cpoly)%>%
  mutate(sc2_hhwacc_pct = sc2_hhwacc/tothh_Cpoly)%>%
  #vehicles with access
  mutate(sc2_vehwacc_SU = sc2_vehwacc_pct*totveh_SU_Cpoly)%>%
  mutate(sc2_vehwacc_duplex = sc2_vehwacc_pct*totveh_duplex_Cpoly)%>%
  mutate(sc2_vehwacc_small = sc2_vehwacc_pct*totveh_small_Cpoly)%>%
  mutate(sc2_vehwacc_large = sc2_vehwacc_pct*totveh_large_Cpoly)%>%
  mutate(sc2_vehwacc_MUD = sc2_vehwacc_pct*totveh_MUD_Cpoly)%>%
  #for all type of housing
  #households with access
  mutate(sc2_hhwacc_SU = sc2_hhwacc_pct*tothh_SU_Cpoly)%>%
  mutate(sc2_hhwacc_duplex = sc2_hhwacc_pct*tothh_duplex_Cpoly)%>%
  mutate(sc2_hhwacc_small = sc2_hhwacc_pct*tothh_small_Cpoly)%>%
  mutate(sc2_hhwacc_large = sc2_hhwacc_pct*tothh_large_Cpoly)%>%
  mutate(sc2_hhwacc_MUD = sc2_hhwacc_pct*tothh_MUD_Cpoly)%>%
  mutate(scenario = "sc2")

cat(" Scenario 2 - All households should have access to an individual level 2 (7.0 kW) charging facility.

    All: We estimate that ",sum(IOU_wacc_sc2$sc2_vehwacc, na.rm = TRUE)," vehicles and ",sum(IOU_wacc_sc2$sc2_hhwacc, na.rm = TRUE)," households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc2$sc2_vehwacc, na.rm = TRUE)/sum(IOU_wacc_sc2$totveh_Cpoly, na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc2$sc2_hhwacc, na.rm = TRUE)/sum(IOU_wacc_sc2$tothh_Cpoly, na.rm = TRUE)*100), "% of all households in PG&E and SCE service territory.
    
    PG&E: We estimate that ", sum(IOU_wacc_sc2$sc2_vehwacc[IOU_wacc_sc2$IOU == "PGE"], na.rm = TRUE), "vehicles and ", sum(IOU_wacc_sc2$sc2_hhwacc[IOU_wacc_sc2$IOU == "PGE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc2$sc2_vehwacc[IOU_wacc_sc2$IOU == "PGE"], na.rm = TRUE)/sum(IOU_wacc_sc2$totveh_Cpoly[IOU_wacc_sc2$IOU == "PGE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc2$sc2_hhwacc[IOU_wacc_sc2$IOU == "PGE"], na.rm = TRUE)/sum(IOU_wacc_sc2$tothh_Cpoly[IOU_wacc_sc2$IOU == "PGE"], na.rm = TRUE)*100), "% of all households in PG&E territory.

    SCE: We estimate that ", sum(IOU_wacc_sc2$sc2_vehwacc[IOU_wacc_sc2$IOU == "SCE"], na.rm = TRUE), "vehicles and ", sum(IOU_wacc_sc2$sc2_hhwacc[IOU_wacc_sc2$IOU == "SCE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc2$sc2_vehwacc[IOU_wacc_sc2$IOU == "SCE"], na.rm = TRUE)/sum(IOU_wacc_sc2$totveh_Cpoly[IOU_wacc_sc2$IOU == "SCE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc2$sc2_hhwacc[IOU_wacc_sc2$IOU == "SCE"], na.rm = TRUE)/sum(IOU_wacc_sc2$tothh_Cpoly[IOU_wacc_sc2$IOU == "SCE"], na.rm = TRUE)*100), "% of all households in SCE territory.")
```

```{r}
#SCENARIO 3
#Shared charging only. Level 2 (7.0 kW) charging infrastructure. One charging infrastructure can support the load of 6.5 vehicles.
IOU_wacc_sc3 <- IOU_wacc %>%
  mutate(sc3_veh_load = totveh_Cpoly/NUM_VEH_CHRG*LVL2_CHRG_PWR)%>%
  mutate(sc3_veh_headroom = ICL_max_hhWt_nadj - sc3_veh_load)%>%
  mutate(sc3_vehwacc = ifelse(sc3_veh_headroom>=0, totveh_Cpoly, totveh_Cpoly*ICL_max_hhWt_nadj/sc3_veh_load))%>%
  mutate(sc3_hhwacc = ifelse(sc3_veh_headroom>=0, tothh_Cpoly, tothh_Cpoly*ICL_max_hhWt_nadj/sc3_veh_load))%>%
  mutate(ICL_hhnoacc = -ifelse(sc3_veh_headroom<0, sc3_veh_headroom/tothh_Cpoly, 0)) %>%
  mutate(sc3_vehwacc_pct = sc3_vehwacc/totveh_Cpoly)%>%
  mutate(sc3_hhwacc_pct = sc3_hhwacc/tothh_Cpoly)%>%
  #for all type of housing
  #vehicles with access
  mutate(sc3_vehwacc_SU = sc3_vehwacc_pct*totveh_SU_Cpoly)%>%
  mutate(sc3_vehwacc_duplex = sc3_vehwacc_pct*totveh_duplex_Cpoly)%>%
  mutate(sc3_vehwacc_small = sc3_vehwacc_pct*totveh_small_Cpoly)%>%
  mutate(sc3_vehwacc_large = sc3_vehwacc_pct*totveh_large_Cpoly)%>%
  mutate(sc3_vehwacc_MUD = sc3_vehwacc_pct*totveh_MUD_Cpoly)%>%
  #households with access
  mutate(sc3_hhwacc_SU = sc3_hhwacc_pct*tothh_SU_Cpoly)%>%
  mutate(sc3_hhwacc_duplex = sc3_hhwacc_pct*tothh_duplex_Cpoly)%>%
  mutate(sc3_hhwacc_small = sc3_hhwacc_pct*tothh_small_Cpoly)%>%
  mutate(sc3_hhwacc_large = sc3_hhwacc_pct*tothh_large_Cpoly)%>%
  mutate(sc3_hhwacc_MUD = sc3_hhwacc_pct*tothh_MUD_Cpoly)%>%
  mutate(scenario = "sc3")

cat(" Scenario 3 - All households should have access to level 2 (7.0 kW) charging facilities close to their homes. One charging infrastructure can support the load of 6.5 vehicles.

    All: We estimate that ",sum(IOU_wacc_sc3$sc3_vehwacc, na.rm = TRUE)," vehicles and ",sum(IOU_wacc_sc3$sc3_hhwacc, na.rm = TRUE)," households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc3$sc3_vehwacc, na.rm = TRUE)/sum(IOU_wacc_sc3$totveh_Cpoly, na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc3$sc3_hhwacc, na.rm = TRUE)/sum(IOU_wacc_sc3$tothh_Cpoly, na.rm = TRUE)*100), "% of all households in PG&E and SCE service territory.
    
    PG&E: We estimate that ", sum(IOU_wacc_sc3$sc3_vehwacc[IOU_wacc_sc3$IOU == "PGE"], na.rm = TRUE), "vehicles and ", sum(IOU_wacc_sc3$sc3_hhwacc[IOU_wacc_sc3$IOU == "PGE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc3$sc3_vehwacc[IOU_wacc_sc3$IOU == "PGE"], na.rm = TRUE)/sum(IOU_wacc_sc3$totveh_Cpoly[IOU_wacc_sc3$IOU == "PGE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc3$sc3_hhwacc[IOU_wacc_sc3$IOU == "PGE"], na.rm = TRUE)/sum(IOU_wacc_sc3$tothh_Cpoly[IOU_wacc_sc3$IOU == "PGE"], na.rm = TRUE)*100), "% of all households in PG&E territory.

    SCE: We estimate that ", sum(IOU_wacc_sc3$sc3_vehwacc[IOU_wacc_sc3$IOU == "SCE"], na.rm = TRUE), "vehicles and ", sum(IOU_wacc_sc3$sc3_hhwacc[IOU_wacc_sc3$IOU == "SCE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc3$sc3_vehwacc[IOU_wacc_sc3$IOU == "SCE"], na.rm = TRUE)/sum(IOU_wacc_sc3$totveh_Cpoly[IOU_wacc_sc3$IOU == "SCE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc3$sc3_hhwacc[IOU_wacc_sc3$IOU == "SCE"], na.rm = TRUE)/sum(IOU_wacc_sc3$tothh_Cpoly[IOU_wacc_sc3$IOU == "SCE"], na.rm = TRUE)*100), "% of all households in SCE territory.")
```

```{r}
#SCENARIO 4
#Mixed charging - per type of housing
#SU --> 1.5kW charging station/hh
#Duplex --> 1/2 * 7.0kW charging station/hh
#smallmulti --> 6.5 veh/charging station
#largemulti --> 6.5 veh/charging station

IOU_wacc_sc4 <- IOU_wacc %>%
  mutate(sc4_veh_load = tothh_SU_Cpoly*LVL1_CHRG_PWR + tothh_duplex_Cpoly/2*LVL2_CHRG_PWR + (totveh_small_Cpoly+totveh_large_Cpoly)/NUM_VEH_CHRG*LVL2_CHRG_PWR )%>%
  mutate(sc4_veh_headroom = ICL_max_hhWt_nadj - sc4_veh_load) %>%
  mutate(sc4_vehwacc = ifelse(sc4_veh_headroom>=0, totveh_Cpoly, totveh_Cpoly*ICL_max_hhWt_nadj/sc4_veh_load))%>%
  mutate(sc4_hhwacc = ifelse(sc4_veh_headroom>=0, tothh_Cpoly, tothh_Cpoly*ICL_max_hhWt_nadj/sc4_veh_load)) %>%
  mutate(ICL_hhnoacc = -ifelse(sc4_veh_headroom<0, sc4_veh_headroom/tothh_Cpoly, 0)) %>%
  mutate(sc4_vehwacc_pct = sc4_vehwacc/totveh_Cpoly)%>%
  mutate(sc4_hhwacc_pct = sc4_hhwacc/tothh_Cpoly)%>%
  #for all type of housing
  #vehicles with access
  mutate(sc4_vehwacc_SU = sc4_vehwacc_pct*totveh_SU_Cpoly)%>%
  mutate(sc4_vehwacc_duplex = sc4_vehwacc_pct*totveh_duplex_Cpoly)%>%
  mutate(sc4_vehwacc_small = sc4_vehwacc_pct*totveh_small_Cpoly)%>%
  mutate(sc4_vehwacc_large = sc4_vehwacc_pct*totveh_large_Cpoly)%>%
  mutate(sc4_vehwacc_MUD = sc4_vehwacc_pct*totveh_MUD_Cpoly)%>%
  #households with access
  mutate(sc4_hhwacc_SU = sc4_hhwacc_pct*tothh_SU_Cpoly)%>%
  mutate(sc4_hhwacc_duplex = sc4_hhwacc_pct*tothh_duplex_Cpoly)%>%
  mutate(sc4_hhwacc_small = sc4_hhwacc_pct*tothh_small_Cpoly)%>%
  mutate(sc4_hhwacc_large = sc4_hhwacc_pct*tothh_large_Cpoly)%>%
  mutate(sc4_hhwacc_MUD = sc4_hhwacc_pct*tothh_MUD_Cpoly)%>%
  mutate(scenario = "sc4")

cat(" Scenario 4 - All households should have access to home charging. Single unit houses have access to level 1 charging (1.5 kW) and MUDs to level 2. The number of charging stations depends on the housing types (see above).
    All: We estimate that ",sum(IOU_wacc_sc4$totveh_Cpoly[IOU_wacc_sc4$sc4_veh_headroom >= 0], na.rm = TRUE)," vehicles and ",sum(IOU_wacc_sc4$tothh_Cpoly[IOU_wacc_sc4$sc4_veh_headroom >= 0], na.rm = TRUE)," households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc4$totveh_Cpoly[IOU_wacc_sc4$sc4_veh_headroom >= 0], na.rm = TRUE)/sum(IOU_wacc_sc4$totveh_Cpoly, na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc4$tothh_Cpoly[IOU_wacc_sc4$sc4_veh_headroom >= 0], na.rm = TRUE)/sum(IOU_wacc_sc4$tothh_Cpoly, na.rm = TRUE)*100), "% of all households in PG&E and SCE service territory.

    PG&E: We estimate that ", sum(IOU_wacc_sc4$sc4_vehwacc[IOU_wacc_sc4$IOU == "PGE"], na.rm = TRUE), "vehicles and ", sum(IOU_wacc_sc4$sc4_hhwacc[IOU_wacc_sc4$IOU == "PGE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc4$sc4_vehwacc[IOU_wacc_sc4$IOU == "PGE"], na.rm = TRUE)/sum(IOU_wacc_sc4$totveh_Cpoly[IOU_wacc_sc4$IOU == "PGE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc4$sc4_hhwacc[IOU_wacc_sc4$IOU == "PGE"], na.rm = TRUE)/sum(IOU_wacc_sc4$tothh_Cpoly[IOU_wacc_sc4$IOU == "PGE"], na.rm = TRUE)*100), "% of all households in PG&E territory.

    SCE: We estimate that ", sum(IOU_wacc_sc4$sc4_vehwacc[IOU_wacc_sc4$IOU == "SCE"], na.rm = TRUE), "vehicles and ", sum(IOU_wacc_sc4$sc4_hhwacc[IOU_wacc_sc4$IOU == "SCE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_wacc_sc4$sc4_vehwacc[IOU_wacc_sc4$IOU == "SCE"], na.rm = TRUE)/sum(IOU_wacc_sc4$totveh_Cpoly[IOU_wacc_sc4$IOU == "SCE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_wacc_sc4$sc4_hhwacc[IOU_wacc_sc4$IOU == "SCE"], na.rm = TRUE)/sum(IOU_wacc_sc4$tothh_Cpoly[IOU_wacc_sc4$IOU == "SCE"], na.rm = TRUE)*100), "% of all households in SCE territory.")
```

-----------------------------------------------
-----------------------------------------------
ACCESS AT COUNTY LEVEL
-----------------------------------------------
-----------------------------------------------

```{r}
#Comparison between Scenarios - GROUPED by COUNTY
#Scenario 1
df_sc1_cty_hh <- select(IOU_wacc_sc1, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("sc1_hhwacc"), starts_with("sc1_hhnoacc")) %>%
  group_by(IOU, county) %>%
  summarise(
            #Calculating total households
            tothh = sum(tothh_Cpoly, na.rm=TRUE),
            #Calculating percentage of households with access
            sc1_cty_wacc_all_pct = sum(sc1_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            sc1_cty_wacc_SU_pct = sum(sc1_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            sc1_cty_wacc_duplex_pct = sum(sc1_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            sc1_cty_wacc_small_pct = sum(sc1_hhwacc_small, na.rm=TRUE)/sum(tothh_small_Cpoly, na.rm=TRUE),
            sc1_cty_wacc_large_pct = sum(sc1_hhwacc_large, na.rm=TRUE)/sum(tothh_large_Cpoly, na.rm=TRUE),
            sc1_cty_wacc_MUD_pct = sum(sc1_hhwacc_MUD, na.rm=TRUE)/sum(tothh_MUD_Cpoly, na.rm=TRUE))

#Scenario 2
df_sc2_cty_hh <- select(IOU_wacc_sc2, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("sc2_hhwacc"), starts_with("sc2_hhnoacc")) %>%
  group_by(IOU, county) %>%
  summarise(
            #Calculating total households
            tothh = sum(tothh_Cpoly, na.rm=TRUE),
            #Calculating percentage of households with access
            sc2_cty_wacc_all_pct = sum(sc2_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            sc2_cty_wacc_SU_pct = sum(sc2_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            sc2_cty_wacc_duplex_pct = sum(sc2_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            sc2_cty_wacc_small_pct = sum(sc2_hhwacc_small, na.rm=TRUE)/sum(tothh_small_Cpoly, na.rm=TRUE),
            sc2_cty_wacc_large_pct = sum(sc2_hhwacc_large, na.rm=TRUE)/sum(tothh_large_Cpoly, na.rm=TRUE),
            sc2_cty_wacc_MUD_pct = sum(sc2_hhwacc_MUD, na.rm=TRUE)/sum(tothh_MUD_Cpoly, na.rm=TRUE))

#Scenario 3
df_sc3_cty_hh <- select(IOU_wacc_sc3, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("sc3_hhwacc"), starts_with("sc3_hhnoacc")) %>%
  group_by(IOU, county) %>%
  summarise(
            #Calculating total households
            tothh = sum(tothh_Cpoly, na.rm=TRUE),
            #Calculating percentage of households with access
            sc3_cty_wacc_all_pct = sum(sc3_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            sc3_cty_wacc_SU_pct = sum(sc3_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            sc3_cty_wacc_duplex_pct = sum(sc3_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            sc3_cty_wacc_small_pct = sum(sc3_hhwacc_small, na.rm=TRUE)/sum(tothh_small_Cpoly, na.rm=TRUE),
            sc3_cty_wacc_large_pct = sum(sc3_hhwacc_large, na.rm=TRUE)/sum(tothh_large_Cpoly, na.rm=TRUE),
            sc3_cty_wacc_MUD_pct = sum(sc3_hhwacc_MUD, na.rm=TRUE)/sum(tothh_MUD_Cpoly, na.rm=TRUE))

#Scenario 4
df_sc4_cty_hh <- select(IOU_wacc_sc4, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("sc4_hhwacc"), starts_with("sc4_hhnoacc")) %>%
  group_by(IOU, county) %>%
  summarise(
            #Calculating total households
            tothh = sum(tothh_Cpoly, na.rm=TRUE),
            #Calculating percentage of households with access
            sc4_cty_wacc_all_pct = sum(sc4_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            sc4_cty_wacc_SU_pct = sum(sc4_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            sc4_cty_wacc_duplex_pct = sum(sc4_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            sc4_cty_wacc_small_pct = sum(sc4_hhwacc_small, na.rm=TRUE)/sum(tothh_small_Cpoly, na.rm=TRUE),
            sc4_cty_wacc_large_pct = sum(sc4_hhwacc_large, na.rm=TRUE)/sum(tothh_large_Cpoly, na.rm=TRUE),
            sc4_cty_wacc_MUD_pct = sum(sc4_hhwacc_MUD, na.rm=TRUE)/sum(tothh_MUD_Cpoly, na.rm=TRUE))


transform_df <- function(df) {
  df %>%
    pivot_longer(
      cols = -c("IOU", "county", "tothh"),
      names_to = c("Scenario", "County_level", "Load", "Housing", ".value"),
      names_sep = "_",
      values_to = "Value"
    )%>%
    select(-c("County_level"))
}

df_county <- bind_rows(
  transform_df(df_sc1_cty_hh),
  transform_df(df_sc2_cty_hh),
  transform_df(df_sc3_cty_hh),
  transform_df(df_sc4_cty_hh)
)

df_county$Housing <- recode(factor(df_county$Housing, levels = c(
  "all", "SU", "duplex", "small", "large", "MUD")),
  "all"= "All", "SU" = "Single Unit", "duplex" = "Duplex",
  "small" = "Small MUD", "large" = "Large MUD", "MUD" = "All MUD (including duplex)"
)

df_county$Scenario <- recode(factor(df_county$Scenario, levels = c(
  "sc1", "sc2", "sc3", "sc4")),
  "sc1"= "Indiv. access (1.5kW)", "sc2"= "Indiv. access (7.0kW)", "sc3"= "Shared access", "sc4" = "Mixed"
)

df_county$Load <- recode(factor(df_county$Load, levels = c(
  "wacc", "noacc150", "noaccinf")),
  "wacc"= "Have access", "noacc150" = "[0-150kW]", "noaccinf" = "[+150kW]"
)
```

```{r}
df_county <- df_county %>%
    filter(!(county == "Alpine"),
           !(county == "Inyo" & IOU == "PGE"),
           !(county == "Mariposa" & IOU == "SCE"),
           !(county == "Mono" & IOU == "PGE"),
           !(county == "Tuolumne" & IOU == "SCE"),
           !(county == "Ventura" & IOU == "PGE"),
           !(county == "Imperial"),
           !(county == "Lassen"),
           !(county == "Madera" & IOU == "SCE"),
           !(county == "San Diego"),
           !(county == "Siskiyou"),
           !(county == "Trinity"))
```

```{r}
#Save data in csv files for PGE and all counties

#Scenario 1 - With Access & All Housing
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "All" & Scenario == "Indiv. access (1.5kW)")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_all/PGE_access_sc1_all.csv", row.names = FALSE)

#Scenario 2 - With Access & All Housing
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "All" & Scenario == "Indiv. access (7.0kW)")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_all/PGE_access_sc2_all.csv", row.names = FALSE)

#Scenario 3 - With Access & All Housing
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "All" & Scenario == "Shared access")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_all/PGE_access_sc3_all.csv", row.names = FALSE)

#Scenario 4 - With Access & All Housing
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "All" & Scenario == "Mixed")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_all/PGE_access_sc4_all.csv", row.names = FALSE)

#Scenario 1 - With Access & Single Unit
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "Single Unit" & Scenario == "Indiv. access (1.5kW)")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_SU/PGE_access_sc1_SU.csv", row.names = FALSE)

#Scenario 2 - With Access & Single Unit
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "Single Unit" & Scenario == "Indiv. access (7.0kW)")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_SU/PGE_access_sc2_SU.csv", row.names = FALSE)

#Scenario 3 - With Access & Single Unit
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "Single Unit" & Scenario == "Shared access")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_SU/PGE_access_sc3_SU.csv", row.names = FALSE)

#Scenario 4 - With Access & Single Unit
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "Single Unit" & Scenario == "Mixed")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_SU/PGE_access_sc4_SU.csv", row.names = FALSE)

#Scenario 1 - With Access & Multiple Unit
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "All MUD (including duplex)" & Scenario == "Indiv. access (1.5kW)")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_MUD/PGE_access_sc1_MUD.csv", row.names = FALSE)

#Scenario 2 - With Access & Multiple Unit
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "All MUD (including duplex)" & Scenario == "Indiv. access (7.0kW)")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_MUD/PGE_access_sc2_MUD.csv", row.names = FALSE)

#Scenario 3 - With Access & Multiple Unit
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "All MUD (including duplex)" & Scenario == "Shared access")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_MUD/PGE_access_sc3_MUD.csv", row.names = FALSE)

#Scenario 4 - With Access & Multiple Unit
PGE_access_all = subset(df_county, IOU == "PGE" & Load == "Have access" & Housing == "All MUD (including duplex)" & Scenario == "Mixed")
write.csv(PGE_access_all, "figures/scenarios/with_access/PGE_MUD/PGE_access_sc4_MUD.csv", row.names = FALSE)
```


-----------------------------------------------
-----------------------------------------------
ACCESS AT IOU LEVEL
-----------------------------------------------
-----------------------------------------------

```{r}
#Comparison between Scenarios - GROUPED by IOU
#Scenario 1
df_sc1_hh <- select(IOU_wacc_sc1, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("sc1_hhwacc"), starts_with("sc1_hhnoacc")) %>%
  group_by(IOU) %>%
  summarise(
            #Calculating total households
            tothh = sum(tothh_Cpoly, na.rm=TRUE),
            #Calculating percentage of households with access
            sc1_wacc_all_pct = sum(sc1_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            sc1_wacc_SU_pct = sum(sc1_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            sc1_wacc_duplex_pct = sum(sc1_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            sc1_wacc_small_pct = sum(sc1_hhwacc_small, na.rm=TRUE)/sum(tothh_small_Cpoly, na.rm=TRUE),
            sc1_wacc_large_pct = sum(sc1_hhwacc_large, na.rm=TRUE)/sum(tothh_large_Cpoly, na.rm=TRUE),
            sc1_wacc_MUD_pct = sum(sc1_hhwacc_MUD, na.rm=TRUE)/sum(tothh_MUD_Cpoly, na.rm=TRUE))

#Scenario 2
df_sc2_hh <- select(IOU_wacc_sc2, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("sc2_hhwacc"), starts_with("sc2_hhnoacc")) %>%
  group_by(IOU) %>%
  summarise(
            #Calculating total households
            tothh = sum(tothh_Cpoly, na.rm=TRUE),
            #Calculating percentage of households with access
            sc2_wacc_all_pct = sum(sc2_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            sc2_wacc_SU_pct = sum(sc2_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            sc2_wacc_duplex_pct = sum(sc2_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            sc2_wacc_small_pct = sum(sc2_hhwacc_small, na.rm=TRUE)/sum(tothh_small_Cpoly, na.rm=TRUE),
            sc2_wacc_large_pct = sum(sc2_hhwacc_large, na.rm=TRUE)/sum(tothh_large_Cpoly, na.rm=TRUE),
            sc2_wacc_MUD_pct = sum(sc2_hhwacc_MUD, na.rm=TRUE)/sum(tothh_MUD_Cpoly, na.rm=TRUE))

#Scenario 3
df_sc3_hh <- select(IOU_wacc_sc3, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("sc3_hhwacc"), starts_with("sc3_hhnoacc")) %>%
  group_by(IOU) %>%
  summarise(
            #Calculating total households
            tothh = sum(tothh_Cpoly, na.rm=TRUE),
            #Calculating percentage of households with access
            sc3_wacc_all_pct = sum(sc3_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            sc3_wacc_SU_pct = sum(sc3_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            sc3_wacc_duplex_pct = sum(sc3_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            sc3_wacc_small_pct = sum(sc3_hhwacc_small, na.rm=TRUE)/sum(tothh_small_Cpoly, na.rm=TRUE),
            sc3_wacc_large_pct = sum(sc3_hhwacc_large, na.rm=TRUE)/sum(tothh_large_Cpoly, na.rm=TRUE),
            sc3_wacc_MUD_pct = sum(sc3_hhwacc_MUD, na.rm=TRUE)/sum(tothh_MUD_Cpoly, na.rm=TRUE))

#Scenario 4
df_sc4_hh <- select(IOU_wacc_sc4, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("sc4_hhwacc"), starts_with("sc4_hhnoacc")) %>%
  group_by(IOU) %>%
  summarise(
            #Calculating total households
            tothh = sum(tothh_Cpoly, na.rm=TRUE),
            #Calculating percentage of households with access
            sc4_wacc_all_pct = sum(sc4_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            sc4_wacc_SU_pct = sum(sc4_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            sc4_wacc_duplex_pct = sum(sc4_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            sc4_wacc_small_pct = sum(sc4_hhwacc_small, na.rm=TRUE)/sum(tothh_small_Cpoly, na.rm=TRUE),
            sc4_wacc_large_pct = sum(sc4_hhwacc_large, na.rm=TRUE)/sum(tothh_large_Cpoly, na.rm=TRUE),
            sc4_wacc_MUD_pct = sum(sc4_hhwacc_MUD, na.rm=TRUE)/sum(tothh_MUD_Cpoly, na.rm=TRUE))

transform_df <- function(df) {
  df %>%
    pivot_longer(
      cols = -c("IOU", "tothh"),
      names_to = c("Scenario", "Load", "Housing", ".value"),
      names_sep = "_",
      values_to = "Value"
    )
}

df_plot <- bind_rows(
  transform_df(df_sc1_hh),
  transform_df(df_sc2_hh),
  transform_df(df_sc3_hh),
  transform_df(df_sc4_hh)
)

df_plot$Housing <- recode(factor(df_plot$Housing, levels = c(
  "all", "SU", "duplex", "small", "large", "MUD")),
  "all"= "All", "SU" = "Single-Unit", "duplex" = "Duplex",
  "small" = "Small MUD", "large" = "Large MUD", "MUD" = "Multi-Unit"
)

df_plot$Scenario <- recode(factor(df_plot$Scenario, levels = c(
  "sc1", "sc2", "sc3", "sc4")),
  "sc1"= "1 - Indiv. access (1.5kW)", "sc2"= "2 - Indiv. access (7.0kW)", "sc3"= "3 - Shared access", "sc4" = "4 - Mixed"
)

df_plot$Load <- recode(factor(df_plot$Load, levels = c(
  "wacc", "noacc150", "noaccinf")),
  "wacc"= "Have access", "noacc150" = "[0-150kW]", "noaccinf" = "[+150kW]"
)
```

Plotting Figure 5.1

```{r}
#Plot - Only hhwacc and PGE
df_plot_access = subset(df_plot, Load == "Have access" & (Housing == "All" | Housing == "Single-Unit" | Housing == "Multi-Unit") & IOU == "PGE")

plot_access <- ggplot(df_plot_access, aes(x = Housing, y = pct, fill = Scenario)) + 
  facet_grid(~ IOU, scales = "free_x", space = "free_x") +
  geom_col(position = position_dodge(width = 0.9)) +  # Adjust 'width' as needed to control the spacing
  scale_fill_manual(values = c("#7EE081", "#62A87C", "#00487C", "#F6F5AE")) +
  labs(title = "",
       x = "",
       y = "Proportion of households with access [%]",
       fill = "Scenario") +
  theme_light() +
  theme(plot.title = element_text(face = "bold", size = 15),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), labels = scales::percent_format(accuracy = 1))

ggsave("figures/scenarios/PGE_access_scenarios_access.png", plot_access, width = 8, height = 5.5)
print(plot_access)
```


```{r}
#Some analysis on PG&E's  access results - Chapter 5

cat("PG&E: We estimate that there is ", sum(IOU_wacc$totveh_Cpoly, na.rm = TRUE), "vehicles and ", sum(IOU_wacc$tothh_Cpoly, na.rm = TRUE), "households on PG&E service territory.
The total capacities needed to accomodate the EV charging facilities according to each charging scenarios are: ", round(sum(IOU_wacc_sc1$sc1_veh_load, na.rm = TRUE)/1000000,1) ,"GW for Scenario 1,", round(sum(IOU_wacc_sc2$sc2_veh_load, na.rm = TRUE)/1000000,1), "GW for Scenario 2,", round(sum(IOU_wacc_sc3$sc3_veh_load, na.rm = TRUE)/1000000,1), "GW for Scenario 3, and", round(sum(IOU_wacc_sc4$sc4_veh_load, na.rm = TRUE)/1000000,1),"GW for Scenario 4.

To accommodate the full spectrum of PG&E households with EV charging capabilities, the electrical infrastructure would need substantial capacity enhancements. Specifically, the required increases are estimated at", round(-sum(IOU_wacc_sc1$sc1_veh_headroom[IOU_wacc_sc1$sc1_veh_headroom < 0], na.rm = TRUE)/1000000,1) ,"GW for Scenario 1,", round(-sum(IOU_wacc_sc2$sc2_veh_headroom[IOU_wacc_sc2$sc2_veh_headroom < 0], na.rm = TRUE)/1000000,1), "GW for Scenario 2,", round(-sum(IOU_wacc_sc3$sc3_veh_headroom[IOU_wacc_sc3$sc3_veh_headroom < 0], na.rm = TRUE)/1000000,1), "GW for Scenario 3, and", round(-sum(IOU_wacc_sc4$sc4_veh_headroom[IOU_wacc_sc4$sc4_veh_headroom < 0], na.rm = TRUE)/1000000,1),"GW for Scenario 4.")
```

-----------------------------------------------
-----------------------------------------------
NO ACCESS AT IOU LEVEL
-----------------------------------------------
-----------------------------------------------

Plotting Figure A.8

```{r}
cs_noaccess <- rbind(select(IOU_wacc_sc1, IOU, tothh_Cpoly, scenario, ICL_hhnoacc),
                     select(IOU_wacc_sc2, IOU, tothh_Cpoly, scenario, ICL_hhnoacc),
                     select(IOU_wacc_sc3, IOU, tothh_Cpoly, scenario, ICL_hhnoacc),
                     select(IOU_wacc_sc4, IOU, tothh_Cpoly, scenario, ICL_hhnoacc)) %>%
  melt(id=c("IOU", "tothh_Cpoly", "scenario")) %>%
  mutate(scenario = recode(factor(scenario, levels=c("sc1","sc2", "sc3", "sc4")), 
                                  'sc1'="1 - Indiv. access (1.5kW)", 'sc2'="2 - Indiv. access (7kW)", 'sc3'="3 - Shared access", 'sc4'="4 - Mixed"))

line_data <- data.frame(
  scenario = c("1 - Indiv. access (1.5kW)", "2 - Indiv. access (7kW)", "3 - Shared access", "4 - Mixed"),
  yintercept = c(1.5, 7, 1.9, 1.38)
)

cs <- cs_noaccess %>% 
  filter(!is.na(value), !(value==0), !(IOU=="SCE")) %>% 
  ggplot(aes(y=value, fill = scenario)) + plotops_csgrid +
    geom_hline(data = line_data, aes(yintercept = yintercept), linetype = "dashed", color = "red", size = 0.8)
cs

ggsave("figures/scenarios/without_access/PGE_deficit_cs_scenarios.png", width=8, height= 4.5)
```

```{r}
PGE_results_noaccess <- cs_noaccess %>%
  filter(!is.na(value), value != 0, IOU != "SCE") %>%
  group_by(scenario) %>%
  summarise(
    tothh = sum(tothh_Cpoly),
    CS_count = n()
  )
```
