---
title: "03_features"
output: html_document
---

This code assembles and cleans features to be used in random forest runs.

```{r}
library(tidyverse)
library(reshape2)
library(ggplot2)
library(stringr)
library(measurements) # https://cran.r-project.org/web/packages/measurements/measurements.pdf
library(colorspace)
library(Hmisc)
```


```{r}
setwd('C:/Users/Louis Rosset/Documents/EPFL/Master Project/Grid_limits_EV_charging/02_cpolys/')
SCEtypes = read.csv("IOUdata/SCE/circuitfiles/SCE_ICAallclasses.csv", header=T, na.strings="?")
SCE_ICAall = read.csv("IOUdata/SCE/circuitfiles/SCE_ICAall.csv", header=T, na.strings="?", colClasses=as.character(SCEtypes$x))

PGE_ICAall = read.csv("IOUdata/PGE/PGE_ICAall.csv", header=T, na.strings="?")
PGE_all = read.csv("IOUdata/PGE/circuitfiles/PGE_all.csv", header=T, na.strings="?")
```

--------------------------------------------------------------------------------------------

COUNTIES

--------------------------------------------------------------------------------------------

Checking of counties line up

```{r}
unique(select(SCE_ICAall, CountyId, county))
unique(select(PGE_ICAall, CountyId, county))
unique(select(PGE_all, CountyId, county))
```

Fixing the NAs:

```{r}
SCE_ICAall$county[SCE_ICAall$CountyId==19] <- "Fresno"
SCE_ICAall$county[SCE_ICAall$CountyId==29] <- "Kern"
SCE_ICAall$county[SCE_ICAall$CountyId==31] <- "Kings"
SCE_ICAall$county[SCE_ICAall$CountyId==37] <- "Los Angeles"
SCE_ICAall$county[SCE_ICAall$CountyId==51] <- "Mono"
SCE_ICAall$county[SCE_ICAall$CountyId==59] <- "Orange"
SCE_ICAall$county[SCE_ICAall$CountyId==65] <- "Riverside"
SCE_ICAall$county[SCE_ICAall$CountyId==71] <- "San Bernardino"
SCE_ICAall$county[SCE_ICAall$CountyId==73] <- "San Diego"
SCE_ICAall$county[SCE_ICAall$CountyId==83] <- "Santa Barbara"
SCE_ICAall$county[SCE_ICAall$CountyId==107] <- "Tulare"
SCE_ICAall$county[SCE_ICAall$CountyId==109] <- "Tuolumne"
SCE_ICAall$county[SCE_ICAall$CountyId==111] <- "Ventura"


PGE_ICAall$county[PGE_ICAall$CountyId==1] <- "Alameda"
PGE_ICAall$county[PGE_ICAall$CountyId==7] <- "Butte"
PGE_ICAall$county[PGE_ICAall$CountyId==5] <- "Amador"
PGE_ICAall$county[PGE_ICAall$CountyId==9] <- "Calaveras"
PGE_ICAall$county[PGE_ICAall$CountyId==11] <- "Colusa"
PGE_ICAall$county[PGE_ICAall$CountyId==13] <- "Contra Costa"
PGE_ICAall$county[PGE_ICAall$CountyId==17] <- "El Dorado"
PGE_ICAall$county[PGE_ICAall$CountyId==19] <- "Fresno"
PGE_ICAall$county[PGE_ICAall$CountyId==21] <- "Glenn"
PGE_ICAall$county[PGE_ICAall$CountyId==23] <- "Humboldt"
PGE_ICAall$county[PGE_ICAall$CountyId==29] <- "Kern"
PGE_ICAall$county[PGE_ICAall$CountyId==31] <- "Kings"
PGE_ICAall$county[PGE_ICAall$CountyId==33] <- "Lake"
PGE_ICAall$county[PGE_ICAall$CountyId==39] <- "Madera"
PGE_ICAall$county[PGE_ICAall$CountyId==41] <- "Marin"
PGE_ICAall$county[PGE_ICAall$CountyId==45] <- "Mendocino"
PGE_ICAall$county[PGE_ICAall$CountyId==47] <- "Merced"
PGE_ICAall$county[PGE_ICAall$CountyId==53] <- "Monterey"
PGE_ICAall$county[PGE_ICAall$CountyId==57] <- "Nevada"
PGE_ICAall$county[PGE_ICAall$CountyId==61] <- "Placer"
PGE_ICAall$county[PGE_ICAall$CountyId==67] <- "Sacramento"
PGE_ICAall$county[PGE_ICAall$CountyId==69] <- "San Benito"
PGE_ICAall$county[PGE_ICAall$CountyId==75] <- "San Francisco"
PGE_ICAall$county[PGE_ICAall$CountyId==77] <- "San Joaquin"
PGE_ICAall$county[PGE_ICAall$CountyId==79] <- "San Luis Obispo"
PGE_ICAall$county[PGE_ICAall$CountyId==81] <- "San Mateo"
PGE_ICAall$county[PGE_ICAall$CountyId==83] <- "Santa Barbara"
PGE_ICAall$county[PGE_ICAall$CountyId==85] <- "Santa Clara"
PGE_ICAall$county[PGE_ICAall$CountyId==87] <- "Santa Cruz"
PGE_ICAall$county[PGE_ICAall$CountyId==89] <- "Shasta"
PGE_ICAall$county[PGE_ICAall$CountyId==95] <- "Solano"
PGE_ICAall$county[PGE_ICAall$CountyId==97] <- "Sonoma"
PGE_ICAall$county[PGE_ICAall$CountyId==99] <- "Stanislaus"
PGE_ICAall$county[PGE_ICAall$CountyId==103] <- "Tehama"
PGE_ICAall$county[PGE_ICAall$CountyId==105] <- "Trinity"
PGE_ICAall$county[PGE_ICAall$CountyId==107] <- "Tulare"
PGE_ICAall$county[PGE_ICAall$CountyId==109] <- "Tuolumne"
PGE_ICAall$county[PGE_ICAall$CountyId==111] <- "Ventura"
PGE_ICAall$county[PGE_ICAall$CountyId==113] <- "Yolo"
PGE_ICAall$county[PGE_ICAall$CountyId==115] <- "Yuba"


PGE_all$county[PGE_all$CountyId==1] <- "Alameda"
PGE_all$county[PGE_all$CountyId==7] <- "Butte"
PGE_all$county[PGE_all$CountyId==5] <- "Amador"
PGE_all$county[PGE_all$CountyId==9] <- "Calaveras"
PGE_all$county[PGE_all$CountyId==11] <- "Colusa"
PGE_all$county[PGE_all$CountyId==13] <- "Contra Costa"
PGE_all$county[PGE_all$CountyId==17] <- "El Dorado"
PGE_all$county[PGE_all$CountyId==19] <- "Fresno"
PGE_all$county[PGE_all$CountyId==21] <- "Glenn"
PGE_all$county[PGE_all$CountyId==23] <- "Humboldt"
PGE_all$county[PGE_all$CountyId==29] <- "Kern"
PGE_all$county[PGE_all$CountyId==31] <- "Kings"
PGE_all$county[PGE_all$CountyId==33] <- "Lake"
PGE_all$county[PGE_all$CountyId==39] <- "Madera"
PGE_all$county[PGE_all$CountyId==41] <- "Marin"
PGE_all$county[PGE_all$CountyId==45] <- "Mendocino"
PGE_all$county[PGE_all$CountyId==47] <- "Merced"
PGE_all$county[PGE_all$CountyId==53] <- "Monterey"
PGE_all$county[PGE_all$CountyId==57] <- "Nevada"
PGE_all$county[PGE_all$CountyId==61] <- "Placer"
PGE_all$county[PGE_all$CountyId==67] <- "Sacramento"
PGE_all$county[PGE_all$CountyId==69] <- "San Benito"
PGE_all$county[PGE_all$CountyId==75] <- "San Francisco"
PGE_all$county[PGE_all$CountyId==77] <- "San Joaquin"
PGE_all$county[PGE_all$CountyId==79] <- "San Luis Obispo"
PGE_all$county[PGE_all$CountyId==81] <- "San Mateo"
PGE_all$county[PGE_all$CountyId==83] <- "Santa Barbara"
PGE_all$county[PGE_all$CountyId==85] <- "Santa Clara"
PGE_all$county[PGE_all$CountyId==87] <- "Santa Cruz"
PGE_all$county[PGE_all$CountyId==89] <- "Shasta"
PGE_all$county[PGE_all$CountyId==95] <- "Solano"
PGE_all$county[PGE_all$CountyId==97] <- "Sonoma"
PGE_all$county[PGE_all$CountyId==99] <- "Stanislaus"
PGE_all$county[PGE_all$CountyId==103] <- "Tehama"
PGE_all$county[PGE_all$CountyId==105] <- "Trinity"
PGE_all$county[PGE_all$CountyId==107] <- "Tulare"
PGE_all$county[PGE_all$CountyId==109] <- "Tuolumne"
PGE_all$county[PGE_all$CountyId==111] <- "Ventura"
PGE_all$county[PGE_all$CountyId==113] <- "Yolo"
PGE_all$county[PGE_all$CountyId==115] <- "Yuba"


unique(select(SCE_ICAall, CountyId, county))
unique(select(PGE_ICAall, CountyId, county))
unique(select(PGE_all, CountyId, county))
nrow(unique(select(PGE_ICAall, CountyId, county)))
```


--------------------------------------------------------------------------------------------

DENSITY

--------------------------------------------------------------------------------------------

Calculate household density

```{r}
SCE_ICAalldemo <- SCE_ICAall %>%
  mutate(hhdensity_hhsqkm = tothh_Cpoly/(CpolyA*conv_unit(1,"m2","km2"))) %>%
  mutate(hhdensity_log = log10(hhdensity_hhsqkm))

PGE_ICAalldemo <- PGE_ICAall %>%
  mutate(hhdensity_hhsqkm = tothh_Cpoly/(CpolyA*conv_unit(1,"m2","km2"))) %>%
  mutate(hhdensity_log = log10(hhdensity_hhsqkm))

PGE_alldemo <- PGE_all %>%
  mutate(hhdensity_hhsqkm = tothh_Cpoly/(CpolyA*conv_unit(1,"m2","km2"))) %>%
  mutate(hhdensity_log = log10(hhdensity_hhsqkm))

is.na(SCE_ICAalldemo) <- do.call(cbind,lapply(SCE_ICAalldemo, is.infinite))
is.na(PGE_ICAalldemo) <- do.call(cbind,lapply(PGE_ICAalldemo, is.infinite))
is.na(PGE_alldemo) <- do.call(cbind,lapply(PGE_alldemo, is.infinite))
```


--------------------------------------------------------------------------------------------

DEMOGRAPHICS

--------------------------------------------------------------------------------------------

Demographic info, created via 01_demodata.Rmd

```{r}
setwd('C:/Users/Louis Rosset/Documents/EPFL/Master Project/Grid_limits_EV_charging/01_demodata')
demotypes = read.csv("bgCAcensusCESclasses.csv", header=T, na.strings="?")
bgCAcensusCES = read.csv("bgCAcensusCES.csv", header=T, na.strings="?", colClasses=as.character(demotypes$x))

colnames(bgCAcensusCES)[colnames(bgCAcensusCES) == "GEOID10"] <- "GEOID"
```

```{r}
demofeatures = c("GEOID", "GEOIDCT", "inc50kbelow_pct", "inc150kplus_pct", "medhhinc",
                 "racediversity", "black_pct", "asian_pct", "nlxwhite_pct", "latinx_pct", 
                 "edavgyrs", "ownerocc_pct", "singleunit_pct", "MUD_pct", "duplex_pct",
                 "smallmulti_pct", "largemulti_pct", "unitsavg", "medyrbuilt", "popvar", 
                 "polexposure_pctl", "polenvt_pctl", "popsens_pctl", "lingisolation_pctl")

SCE_ICAalldemo <- SCE_ICAalldemo %>% merge(bgCAcensusCES[, demofeatures], by="GEOID", all.x=TRUE) %>% unique()
PGE_ICAalldemo <- PGE_ICAalldemo %>% merge(bgCAcensusCES[, demofeatures], by="GEOID", all.x=TRUE) %>% unique()
PGE_alldemo <- PGE_alldemo %>% merge(bgCAcensusCES[, demofeatures], by="GEOID", all.x=TRUE) %>% unique()
```

Subset to remove unrealistic population totals:

```{r}
SCE_ICAalldemo_real = subset(SCE_ICAalldemo, tothh_Cpoly >= 1)
PGE_ICAalldemo_real = subset(PGE_ICAalldemo, tothh_Cpoly >= 1)
PGE_alldemo_real = subset(PGE_alldemo, tothh_Cpoly >= 1)
```


```{r}
setwd('C:/Users/Louis Rosset/Documents/EPFL/Master Project/Grid_limits_EV_charging/03_features')

#PG&E
write.csv(PGE_ICAalldemo, file = "IOUdata/PGE/circuitfiles/PGE_ICAalldemo.csv", row.names = FALSE)
write.csv(PGE_ICAalldemo_real, file = "IOUdata/PGE/circuitfiles/PGE_ICAalldemoreal.csv", row.names = FALSE)

write.csv(PGE_alldemo, file = "IOUdata/PGE/circuitfiles/PGE_alldemo.csv", row.names = FALSE)
#write.csv(PGE_alldemo_real, file = "circuitfiles/PGE_alldemoreal.csv", row.names = FALSE)

PGEtypes <- sapply(PGE_ICAalldemo,class)
write.csv(PGEtypes, file = "IOUdata/PGE/circuitfiles/PGE_ICAalldemoclasses.csv", row.names=FALSE)

#SCE
write.csv(SCE_ICAalldemo, file = "IOUdata/SCE/circuitfiles/SCE_ICAalldemo.csv", row.names = FALSE)
write.csv(SCE_ICAalldemo_real, file = "IOUdata/SCE/circuitfiles/SCE_ICAalldemoreal.csv", row.names = FALSE)

SCEtypes <- sapply(SCE_ICAalldemo,class)
write.csv(SCEtypes, file = "IOUdata/SCE/circuitfiles/SCE_ICAalldemoclasses.csv", row.names=FALSE)
```


Visualizations

```{r}
demof = c("medhhinc","inc50kbelow_pct","inc150kplus_pct","racediversity",
          "nlxwhite_pct","black_pct","latinx_pct","asian_pct",
          "ownerocc_pct","singleunit_pct", "MUD_pct", "duplex_pct",
          "smallmulti_pct", "largemulti_pct", "unitsavg","medyrbuilt", "popvar",
          "polexposure_pctl","polenvt_pctl","popsens_pctl","lingisolation_pctl",
          "edavgyrs","tothh","hhdensity_hhsqkm" )

cols = c("GEOID","CircuitName","IOU","tothh_Cpoly",demof)

demovizPGE <- PGE_ICAalldemo_real[,cols]
demovizPGEall <- PGE_alldemo_real[,cols] %>% mutate(IOU = "PGEall")
demovizSCE <- SCE_ICAalldemo_real[,cols]

perc = c(0.1,0.25,0.5,0.75,0.9)

demovizPGEq <- as.data.frame(sapply(demovizPGE[,demof], wtd.quantile, probs=perc, weight=demovizPGE$tothh_Cpoly, na.rm=TRUE))
demovizPGEq <- cbind(rownames(demovizPGEq), data.frame(demovizPGEq, row.names=NULL))
colnames(demovizPGEq)[1] <- "Percentile"
demovizPGEq <- mutate(demovizPGEq, IOU="PGE")

demovizPGEallq <- as.data.frame(sapply(demovizPGEall[,demof], wtd.quantile, probs=perc, weight=demovizPGEall$tothh_Cpoly, na.rm=TRUE))
demovizPGEallq <- cbind(rownames(demovizPGEallq), data.frame(demovizPGEallq, row.names=NULL))
colnames(demovizPGEallq)[1] <- "Percentile"
demovizPGEallq <- mutate(demovizPGEallq, IOU="PGEall")

demovizSCEq <- as.data.frame(sapply(demovizSCE[,demof], wtd.quantile, probs=perc, weight=demovizSCE$tothh_Cpoly, na.rm=TRUE))
demovizSCEq <- cbind(rownames(demovizSCEq), data.frame(demovizSCEq, row.names=NULL))
colnames(demovizSCEq)[1] <- "Percentile"
demovizSCEq <- mutate(demovizSCEq, IOU="SCE")

demovizq <- rbind(demovizPGEq, demovizPGEallq, demovizSCEq) %>% melt(id=c("Percentile","IOU")) %>% 
  mutate(IOU = factor(IOU, levels=c("PGE","PGEall","SCE")), variable = factor(variable, levels=demof)) %>%
  mutate(value = ifelse(str_sub(variable,-4,-1)=="_pct",value*100,value))

demoviz <- rbind(demovizPGE, demovizPGEall, demovizSCE) %>% melt(id=c("GEOID","CircuitName","IOU","tothh_Cpoly")) %>%
  mutate(IOU = factor(IOU, levels=c("PGE","PGEall","SCE")), variable = factor(variable, levels=demof)) %>%
  mutate(value = ifelse(str_sub(variable,-4,-1)=="_pct",value*100,value))

ggplot(demoviz, aes(y=value)) + theme_light() + facet_wrap(~variable, scales="free_y", ncol=4) +
  stat_density(data=subset(demoviz, IOU=="PGE"), aes(x=-..scaled.., y=value, weight=tothh_Cpoly, fill=IOU), alpha=0.3, adjust=1/2) +
  stat_density(data=subset(demoviz, IOU=="PGEall"), aes(x=-..scaled.., y=value, weight=tothh_Cpoly, fill=IOU), alpha=0.3, adjust=1/2) +
  stat_density(data=subset(demoviz, IOU=="SCE"), aes(x=..scaled.., y=value, weight=tothh_Cpoly, fill=IOU), alpha=0.3, adjust=1/2) +
  geom_segment(data=subset(demovizq, IOU=="PGE"), aes(x=-0.25, xend=0, y=value, yend=value, color=IOU), inherit.aes=FALSE) +
  geom_segment(data=subset(demovizq, IOU=="PGEall"), aes(x=-0.25, xend=0, y=value, yend=value, color=IOU), inherit.aes=FALSE) +
  geom_segment(data=subset(demovizq, IOU=="SCE"), aes(x=0, xend=0.25, y=value, yend=value, color=IOU), inherit.aes=FALSE) +
  geom_vline(xintercept=0) + theme(legend.position="bottom") +
  #scale_fill_manual(values = c("≥"="forestgreen", "<"="indianred3")) +
  #scale_color_discrete_sequential(palette="Grays", nmax=7, order=3:7) +
  scale_color_manual(values=c("PGE"="coral3", "PGEall"="forestgreen", "SCE"="dodgerblue4"), 
                     labels=c("PG&E, ICA data available", "PG&E, full territory", "SCE")) +
  scale_fill_discrete(labels=c("PG&E, ICA data available", "PG&E, full territory", "SCE")) +
  scale_x_continuous(breaks=c(-1.0,-0.5,0.0,0.5,1.0), labels=c("1","0.5","0","0.5","1")) +
  guides(fill = guide_legend(override.aes=list(alpha=0.3))) +
  labs(x="Relative density of households", y="Demographic variable", fill="IOU")
  
ggsave("IOU_demo_wrap.png", path="figures/", width=12, height=8)
ggsave("IOU_demo_wrap.pdf", path="figures/", width=12, height=8)

rm(demovizSCE, demovizPGE, demovizPGEall, demovizSCEq, demovizPGEq, demovizPGEallq, demoviz, demovizq)
```





