---
title: "Access_MUD"
author: "Louis Rosset"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(knitr)
library(gridExtra)
library(cowplot)
```

```{r}
setwd('C:/Users/Louis Rosset/Documents/EPFL/Master Project/QGIS_data/04_allocation/IOUdata/SCE')

SCEtypes <- read.csv("circuitfiles/SCE_ICAalldemoallocclasses.csv", header = TRUE, na.strings = "?")
SCE_ICAaccess <- read.csv("circuitfiles/SCE_ICAalldemoalloc.csv", header = TRUE, na.strings = "?", colClasses = as.character(SCEtypes$x))

setwd('C:/Users/Louis Rosset/Documents/EPFL/Master Project/QGIS_data/04_allocation/IOUdata/PGE')

PGEtypes <- read.csv("circuitfiles/PGE_ICAalldemoallocclasses.csv", header = TRUE, na.strings = "?")
PGE_ICAaccess <- read.csv("circuitfiles/PGE_ICAalldemoalloc.csv", header = TRUE, na.strings = "?", colClasses = as.character(PGEtypes$x))
```

```{r}
# B25024 - UNITS IN STRUCTURE, including number of structures
setwd('C:/Users/Louis Rosset/Documents/EPFL/Master Project/QGIS_data/Aggregate_Data_updated')

ACS_2021_bg_units = read.csv("blockgroup/ACS_21_5YR_B25024_with_ann.csv", header=T, sep = ";", skip=1, na.strings="null", colClasses=c("factor", "factor", "character",rep("character",22)))
colnames(ACS_2021_bg_units) <- c("GEOid_bg", "GEOID10", "bgcountystate", "totstr", "totstr_err", "units1det", "units1det_err", "units1att", "units1att_err", "units2", "units2_err", "units3to4", "units3to4_err", "units5to9", "units5to9_err", "units10to19", "units10to19_err", "units20to49", "units20to49_err", "units50plus", "units50plus_err", "mobilehome", "mobilehome_err", "boatrvvan", "boatrvvan_err")
# Convert the last 22 columns to numeric and remove double quotes
ACS_2021_bg_units <- ACS_2021_bg_units %>%
  mutate_at(vars(tail(names(.), 22)), ~as.numeric(gsub('"', '', .)))
# creating some new summary columns
ACS_2021_bg_units <- ACS_2021_bg_units %>%
  mutate(singleunit = units1att + units1det,
         duplex = units2,
         smallmulti = units3to4 + units5to9 + units10to19,
         largemulti = units20to49 + units50plus,
         totstr_wout_extra = totstr - mobilehome - boatrvvan) %>%
  mutate(singleunit_pct = singleunit / totstr_wout_extra,
         duplex_pct = duplex / totstr_wout_extra,
         smallmulti_pct = smallmulti / totstr_wout_extra,
         largemulti_pct = largemulti / totstr_wout_extra) %>%
  mutate(unitsavg = (singleunit*1 + duplex*2 + units3to4*3.5 + units5to9*7 + units10to19*14.5 + units20to49*34.5 + units50plus*50) / totstr_wout_extra)
```

```{r}
PGE_ICAaccess <- merge(PGE_ICAaccess, ACS_2021_bg_units[, c("GEOID10", "singleunit", "duplex", "smallmulti", "largemulti", "duplex_pct", "smallmulti_pct", "largemulti_pct")], by = "GEOID10")

PGE_ICAaccess_filtered <- PGE_ICAaccess[, c("CircuitName", "GEOID", "ICL_kWphh", "ICL_max", "totstr_pct", "totstr_Cpoly", "ICL_max_ctot", "unitsavg", "singleunit", "duplex", "smallmulti", "largemulti", "singleunit_pct", "duplex_pct", "smallmulti_pct", "largemulti_pct")]

PGE_ICAaccess_filtered <- PGE_ICAaccess_filtered %>%
  mutate(ICL_max_strWt = ICL_max * totstr_pct) %>%
  mutate(normstr_ICL = ICL_max_strWt/ICL_max_ctot) %>%
  mutate(normstr_ICL = ifelse((is.na(normstr_ICL)|is.infinite(normstr_ICL)|normstr_ICL==0), 1, normstr_ICL))%>%
  mutate(ICL_max_strWt_n = ICL_max_strWt/normstr_ICL)%>%
  mutate(ICL_max_strWt_nadj = ifelse(abs(ICL_max_strWt_n)<abs(ICL_max), ICL_max_strWt_n, ICL_max))%>%
  mutate(ICL_kWstr = ICL_max_strWt_nadj / totstr_Cpoly)%>%
  mutate(MUD_pct = duplex_pct + smallmulti_pct + largemulti_pct)
```

```{r}
SCE_ICAaccess <- merge(SCE_ICAaccess, ACS_2021_bg_units[, c("GEOID10", "singleunit", "duplex", "smallmulti", "largemulti", "duplex_pct", "smallmulti_pct", "largemulti_pct")], by.x = "GEOID", by.y = "GEOID10")

SCE_ICAaccess_filtered <- SCE_ICAaccess[, c("CircuitName", "GEOID", "ICL_kWphh", "ICL_max", "totstr_pct", "totstr_Cpoly", "ICL_max_ctot", "unitsavg", "singleunit", "duplex", "smallmulti", "largemulti", "singleunit_pct", "duplex_pct", "smallmulti_pct", "largemulti_pct")]

SCE_ICAaccess_filtered <- SCE_ICAaccess_filtered %>%
  mutate(ICL_max_strWt = ICL_max * totstr_pct) %>%
  mutate(normstr_ICL = ICL_max_strWt/ICL_max_ctot) %>%
  mutate(normstr_ICL = ifelse((is.na(normstr_ICL)|is.infinite(normstr_ICL)|normstr_ICL==0), 1, normstr_ICL))%>%
  mutate(ICL_max_strWt_n = ICL_max_strWt/normstr_ICL)%>%
  mutate(ICL_max_strWt_nadj = ifelse(abs(ICL_max_strWt_n)<abs(ICL_max), ICL_max_strWt_n, ICL_max))%>%
  mutate(ICL_kWstr = ICL_max_strWt_nadj / totstr_Cpoly)%>%
  mutate(MUD_pct = duplex_pct + smallmulti_pct + largemulti_pct)
```

```{r}
# Create a vector of capacity thresholds
capacity_thresholds <- c(0, 1.5, 2, 3, 4, 4.5, 5, 6, 7, 8, 9, 10)

# Initialize an empty vector to store proportions for PGE and SCE
proportions_pge <- numeric(length(capacity_thresholds))
proportions_sce <- numeric(length(capacity_thresholds))

# Calculate the proportion of households with access for each threshold for PGE
for (i in 1:length(capacity_thresholds)) {
  threshold <- capacity_thresholds[i]
  households_with_access <- sum(PGE_ICAaccess_filtered$ICL_kWstr > threshold, na.rm = TRUE)
  proportions_pge[i] <- households_with_access / nrow(PGE_ICAaccess_filtered) * 100
}

# Calculate the proportion of households with access for each threshold for SCE
for (i in 1:length(capacity_thresholds)) {
  threshold <- capacity_thresholds[i]
  households_with_access <- sum(SCE_ICAaccess_filtered$ICL_kWstr > threshold, na.rm = TRUE)
  proportions_sce[i] <- households_with_access / nrow(SCE_ICAaccess_filtered) * 100
}

# Create a data frame for the results for PGE
access_summary_pge <- data.frame(Capacity_Threshold = capacity_thresholds, Proportion = proportions_pge)

# Create a data frame for the results for SCE
access_summary_sce <- data.frame(Capacity_Threshold = capacity_thresholds, Proportion = proportions_sce)

# Create the plot for PGE
plot_pge <- ggplot(access_summary_pge, aes(x = Capacity_Threshold, y = Proportion)) +
  geom_line(size = 1) +
  geom_point(size = 3) +
  labs(title = "PGE",
       x = "Access Threshold (kW)",
       y = "Proportion of Structures with Access (%)") +
  scale_x_continuous(breaks = capacity_thresholds, 
                     labels = c(">0", "1.5", "2", "3", "4", "4.5", "5", "6", "7", "8", "9", "10")) +
  scale_y_continuous(labels = scales::percent_format(scale = 1), 
                     limits = c(0, 100), 
                     breaks = c(0, 20, 40, 60, 80, 100))

# Create the plot for SCE
plot_sce <- ggplot(access_summary_sce, aes(x = Capacity_Threshold, y = Proportion)) +
  geom_line(size = 1) +
  geom_point(size = 3) +
  labs(title = "SCE",
       x = "Access Threshold (kW)",
       y = "Proportion of Structures with Access (%)") +
  scale_x_continuous(breaks = capacity_thresholds, 
                     labels = c(">0", "1.5", "2", "3", "4", "4.5", "5", "6", "7", "8", "9", "10")) +
  scale_y_continuous(labels = scales::percent_format(scale = 1), 
                     limits = c(0, 100), 
                     breaks = c(0, 20, 40, 60, 80, 100))

# Create a single figure with plots for PGE and SCE side by side
combined_plot <- grid.arrange(plot_pge, plot_sce, ncol = 2)

# Save the combined plot as an image file (e.g., PNG) with appropriate dimensions
# Replace 'plot_output.png' with your desired file name and format
ggsave("figures/access/plot_IOU__str_access.png", combined_plot, width = 12, height = 6)
```


| IOU straccess by unitsavg |

```{r}
# Function to calculate proportions
calculate_proportions <- function(data, thresholds) {
  sapply(thresholds, function(th) {
    sum(data$ICL_kWstr > th, na.rm = TRUE) / nrow(data) * 100
  })
}

# Function to generate plots
generate_plot <- function(data_filtered, title) {
  # Define the ranges and categories
  ranges <- list(c(0, 1), c(1, 2), c(2, 3), c(3, 4.5), c(4.5, 9.5), c(9.5, Inf))
  categories <- c("[0-1]", "[1-2]", "[2-3]", "[3-4.5]", "[4.5-9.5]", "[9.5+]")
  thresholds <- c(0, 1.5, 2, 3, 4, 4.5, 5, 6, 7, 8, 9, 10)
  
  plot_data <- do.call(rbind, lapply(seq_along(ranges), function(i) {
    data_filtered <- data_filtered %>% filter(unitsavg >= ranges[[i]][1] & unitsavg < ranges[[i]][2])
    proportions <- calculate_proportions(data_filtered, thresholds)
    
    data.frame(
      Threshold = thresholds,
      Proportion = proportions,
      Category = categories[i]
    )
  }))
  
  ggplot(plot_data, aes(x = Threshold, y = Proportion, color = Category, group = Category)) +
    geom_line(size = 1) +
    geom_point(size = 3) +
    scale_color_manual(values = c(
      "[0-1]" = "steelblue1",
      "[1-2]" = "steelblue2",
      "[2-3]" = "steelblue3",
      "[3-4.5]" = "steelblue4",
      "[4.5-9.5]" = "midnightblue",
      "[9.5+]" = "black"
    )) +
    scale_x_continuous(breaks = thresholds,
                       labels = c(">0", "1.5", "2", "3", "4", "4.5", "5", "6", "7", "8", "9", "10")) +
    scale_y_continuous(labels = scales::percent_format(scale = 1),
                       limits = c(0, 100),
                       breaks = c(0, 20, 40, 60, 80, 100)) +
    labs(
      title = title,
      x = "Access threshold (kW)",
      y = "Proportion of structures with access",
      color = "Number of units"
    ) +
    theme_minimal()
}

# Applying the function to create plots
PGE_straccess <- generate_plot(PGE_ICAaccess_filtered, "PGE")
SCE_straccess <- generate_plot(SCE_ICAaccess_filtered, "SCE")

# Combining and saving the plots
combined_plot_str <- grid.arrange(PGE_straccess, SCE_straccess, ncol = 2,
                                 bottom = "Structure access considering the average number of units within a circuit polygon")

ggsave("figures/access/plot_IOU_straccess_by_units.png", combined_plot_str, width = 12, height = 6)
```

| IOU phhaccess by MUD_pct |

```{r}
# Function to calculate proportions
calculate_proportions <- function(data, thresholds) {
  sapply(thresholds, function(th) {
    sum(data$ICL_kWstr > th, na.rm = TRUE) / nrow(data) * 100
  })
}

# Function to generate plots
generate_plot <- function(data_filtered, title) {
  # Define the ranges and categories
  ranges <- list(c(0, 0.2), c(0.2, 0.4), c(0.4, 0.6), c(0.6, 0.8), c(0.8, 1))
  categories <- c("[0-0.2]", "[0.2-0.4]", "[0.4-0.6]", "[0.6-0.8]", "[0.8-1]")
  thresholds <- c(0, 1.5, 2, 3, 4, 4.5, 5, 6, 7, 8, 9, 10)
  
  plot_data <- do.call(rbind, lapply(seq_along(ranges), function(i) {
    data_filtered <- data_filtered %>% filter(MUD_pct >= ranges[[i]][1] & MUD_pct < ranges[[i]][2])
    proportions <- calculate_proportions(data_filtered, thresholds)
    
    data.frame(
      Threshold = thresholds,
      Proportion = proportions,
      Category = categories[i]
    )
  }))
  
  ggplot(plot_data, aes(x = Threshold, y = Proportion, color = Category, group = Category)) +
    geom_line(size = 1) +
    geom_point(size = 3) +
    scale_color_manual(values = c(
      "[0-0.2]" = "steelblue1",
      "[0.2-0.4]" = "steelblue2",
      "[0.4-0.6]" = "steelblue3",
      "[0.6-0.8]" = "steelblue4",
      "[0.8-1]" = "midnightblue"
    )) +
    scale_x_continuous(breaks = thresholds,
                       labels = c(">0", "1.5", "2", "3", "4", "4.5", "5", "6", "7", "8", "9", "10")) +
    scale_y_continuous(labels = scales::percent_format(scale = 1),
                       limits = c(0, 100),
                       breaks = c(0, 20, 40, 60, 80, 100)) +
    labs(
      title = title,
      x = "Access threshold (kW)",
      y = "Proportion of structures with access",
      color = "Percentage of MUDs"
    ) +
    theme_minimal()
}

# Applying the function to create plots
PGE_straccess_MUD <- generate_plot(PGE_ICAaccess_filtered, "PGE")
SCE_straccess_MUD <- generate_plot(SCE_ICAaccess_filtered, "SCE")
```

```{r}
# Function to calculate proportions
calculate_proportions <- function(data, thresholds) {
  sapply(thresholds, function(th) {
    sum(data$ICL_kWphh > th, na.rm = TRUE) / nrow(data) * 100
  })
}

# Function to generate plots
generate_plot <- function(data_filtered, title) {
  # Define the ranges and categories
  ranges <- list(c(0, 0.2), c(0.2, 0.4), c(0.4, 0.6), c(0.6, 0.8), c(0.8, 1))
  categories <- c("[0-0.2]", "[0.2-0.4]", "[0.4-0.6]", "[0.6-0.8]", "[0.8-1]")
  thresholds <- c(0, 1.5, 2, 3, 4, 4.5, 5, 6, 7, 8, 9, 10)
  
  plot_data <- do.call(rbind, lapply(seq_along(ranges), function(i) {
    data_filtered <- data_filtered %>% filter(MUD_pct >= ranges[[i]][1] & MUD_pct < ranges[[i]][2])
    proportions <- calculate_proportions(data_filtered, thresholds)
    
    data.frame(
      Threshold = thresholds,
      Proportion = proportions,
      Category = categories[i]
    )
  }))
  
  ggplot(plot_data, aes(x = Threshold, y = Proportion, color = Category, group = Category)) +
    geom_line(size = 1) +
    geom_point(size = 3) +
    scale_color_manual(values = c(
      "[0-0.2]" = "steelblue1",
      "[0.2-0.4]" = "steelblue2",
      "[0.4-0.6]" = "steelblue3",
      "[0.6-0.8]" = "steelblue4",
      "[0.8-1]" = "midnightblue"
    )) +
    scale_x_continuous(breaks = thresholds,
                       labels = c(">0", "1.5", "2", "3", "4", "4.5", "5", "6", "7", "8", "9", "10")) +
    scale_y_continuous(labels = scales::percent_format(scale = 1),
                       limits = c(0, 100),
                       breaks = c(0, 20, 40, 60, 80, 100)) +
    labs(
      title = title,
      x = "Access threshold (kW)",
      y = "Proportion of households with access",
      color = "Percentage of MUDs"
    ) +
    theme_minimal()
}

# Applying the function to create plots
PGE_hhaccess_MUD <- generate_plot(PGE_ICAaccess_filtered, "PGE")
SCE_hhaccess_MUD <- generate_plot(SCE_ICAaccess_filtered, "SCE")
```

```{r}
# Combining and saving the plots
combined_plot_str_MUD <- grid.arrange(PGE_straccess_MUD, SCE_straccess_MUD, ncol = 2,
                                 bottom = "Household access considering the percentage of MUDs within a circuit polygon")

ggsave("figures/access/plot_IOU_hhaccess_MUD.png", combined_plot_str_MUD, width = 12, height = 6)
```


```{r}
# Hide the legends in each individual plot
plots <- list(PGE_straccess_MUD, SCE_straccess_MUD, PGE_hhaccess_MUD, SCE_hhaccess_MUD)
plots_no_legend <- lapply(plots, function(p) p + theme(legend.position = "none"))

# Extract the legend
legend <- cowplot::get_legend(plots[[1]])

# Combine the plots and the legend
combined_plot_MUD <- cowplot::plot_grid(
  plot_grid(plotlist = plots_no_legend, ncol = 2),
  legend,
  ncol = 2,
  rel_widths = c(1, 0.2)
)

# Save the combined plot
ggsave("figures/access/plot_IOU_access_MUD.png", combined_plot_MUD, width = 12, height = 6)
```

