---
title: "05_access"
output: html_notebook
---

This notebook calculates grid access for households in PG&E and SCE service territories.

VERSION N°4 - Adding housing data per type

```{r}
library(tidyverse)
library(tictoc)
library(reshape2)
library(ggplot2)
library(stringr)
library(tidytext)
library(measurements) # https://cran.r-project.org/web/packages/measurements/measurements.pdf
library(readxl)
library(colorspace)
library(cowplot)
library(gridExtra)
```

```{r}
setwd('C:/Users/Louis Rosset/Documents/EPFL/Master Project/QGIS_data/04_allocation/IOUdata')
SCEtypes = read.csv("SCE/circuitfiles/SCE_ICAalldemoallocclasses.csv", header=T, na.strings="?")
SCE_ICAaccess = read.csv("SCE/circuitfiles/SCE_ICAalldemoalloc.csv", header=T, na.strings="?", colClasses=as.character(SCEtypes$x))

setwd('C:/Users/Louis Rosset/Documents/EPFL/Master Project/QGIS_data/04_allocation/IOUdata')
PGEtypes = read.csv("PGE/circuitfiles/PGE_ICAalldemoallocclasses.csv", header=T, na.strings="?")
PGE_ICAaccess = read.csv("PGE/circuitfiles/PGE_ICAalldemoalloc.csv", header=T, na.strings="?", colClasses=as.character(PGEtypes$x))

at <- c("1", "1.5", "2.0", "3.0", "4.0", "4.5", "5.0", "6.0", "7.0", "8.0", "9.0", "10.")

###EXTRA FEATURES FOR HOUSING###
SCEhousingtypes <- read.csv("SCE/circuitfiles/SCE_ICAalldemo_housing_classes.csv", header = TRUE, na.strings = "?")
SCE_ICA_housing <- read.csv("SCE/circuitfiles/SCE_ICAalldemoalloc_housing.csv", header = TRUE, na.strings = "?", colClasses = as.character(SCEhousingtypes$x))

PGEhousingtypes <- read.csv("PGE/circuitfiles/PGE_ICAalldemo_housing_classes.csv", header = TRUE, na.strings = "?")
PGE_ICA_housing <- read.csv("PGE/circuitfiles/PGE_ICAalldemoalloc_housing.csv", header = TRUE, na.strings = "?", colClasses = as.character(PGEhousingtypes$x))

#Correcting some duplicates problem
PGE_ICAaccess <- PGE_ICAaccess[!duplicated(PGE_ICAaccess[, c("GEOID", "CircuitName")]), ]
PGE_ICA_housing <- PGE_ICA_housing[!duplicated(PGE_ICA_housing[, c("GEOID", "CircuitName")]), ]

SCE_ICAaccess <- merge(SCE_ICAaccess, 
                       SCE_ICA_housing[, c("GEOID", "CircuitName", "MUD_pct", "duplex_pct", "smallmulti_pct", "largemulti_pct")], 
                       by = c("GEOID", "CircuitName"))

SCE_ICAaccess <- merge(SCE_ICAaccess, SCE_ICA_housing[, c("GEOID", "CircuitName", "tothh_Cpoly", "tothh_SU_Cpoly", "tothh_duplex_Cpoly", "tothh_3to4_Cpoly", "tothh_5to9_Cpoly", "tothh_10to19_Cpoly", "tothh_20to49_Cpoly", "tothh_50plus_Cpoly")], by = c("GEOID", "CircuitName", "tothh_Cpoly"))

PGE_ICAaccess <- merge(PGE_ICAaccess, 
                       PGE_ICA_housing[, c("GEOID", "CircuitName", "MUD_pct", "duplex_pct", "smallmulti_pct", "largemulti_pct")], 
                       by = c("GEOID", "CircuitName"))

PGE_ICAaccess <- merge(PGE_ICAaccess, PGE_ICA_housing[, c("GEOID", "CircuitName", "tothh_Cpoly", "tothh_SU_Cpoly", "tothh_duplex_Cpoly", "tothh_3to4_Cpoly", "tothh_5to9_Cpoly", "tothh_10to19_Cpoly", "tothh_20to49_Cpoly", "tothh_50plus_Cpoly")], by = c("GEOID", "CircuitName", "tothh_Cpoly"))

rm(PGE_ICA_housing, SCE_ICA_housing, PGEhousingtypes, SCEhousingtypes, PGEtypes, SCEtypes)
### ------------------------###
```
Importing vehicle's ownership data
```{r}
# Estimated average number of vehicles per household in 2017-2021, at Census Block Group level (Source: ACS 5-years average - found on https://ucberkeley.policymap.com/)
setwd('C:/Users/Louis Rosset/Documents/EPFL/Master Project/QGIS_data/Vehicles/')
ACS_bg_vehicles_hh = read.csv("Average_number_of_vehicles_per_household.csv", header = TRUE, skip = 1, na.strings = "?")
ACS_bg_vehicles_hh <- ACS_bg_vehicles_hh %>%
  select(GEOID = GeoID_Name, avgveh_hh = avmv) %>%
  mutate(GEOID = as.character(GEOID), 
         avgveh_hh = as.numeric(avgveh_hh))
```

```{r}
labsIOU <- function(x) ifelse(x == "PGE", "PG&E", "SCE")
labsDER <- function(x) ifelse(x == "ICL", "Load", NA)
housing <- c("SU", "duplex", "3to4", "5to9", "10to19", "20to49", "50plus")
```

--------------------------------------------------------------------------------------------

GRID LIMITS

--------------------------------------------------------------------------------------------

```{r}
plotops_bggrid = list(
  theme_light(), facet_grid(IOU~DER, scales="free_x", space='free_x', labeller=labeller(IOU=labsIOU, DER=labsDER)),
  geom_boxplot(aes(fill=threshold), alpha=1, width=0.9), scale_fill_discrete_sequential(palette="Mint", nmax=13, order=1:13), 
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), legend.position="bottom"), guides(fill=guide_legend(nrow=1)), 
  scale_y_continuous(limits=c(0,1), breaks=c(0,0.2,0.4,0.6,0.8,1), labels=scales::percent_format(accuracy=1)), 
  labs(x="", y="Portion of households with access, by block group", fill="Access threshold (kW)")
)

plotops_allgrid = list(theme_light(), facet_grid(IOU~DER, labeller=labeller(IOU=labsIOU)),
  geom_line(), geom_point(size=2), 
  theme(legend.position="bottom", legend.margin=margin(), legend.text=element_text(size=8), axis.text.x=element_text(size=7)),
  guides(shape=guide_legend(nrow=4,title.position="top")),
  scale_y_continuous(limits=c(0,1), breaks=c(0,0.2,0.4,0.6,0.8,1), labels=scales::percent_format(accuracy=1)),
  scale_x_continuous(breaks=c(0,as.numeric(at)), labels=c(">0", "1", "1.5","2","3","4","4.5","5","6","7","8","9","10")),
  scale_color_discrete_sequential(palette="Viridis", nmax=5, order=5:2),
  labs(x="Access threshold (kW)", y="Portion of households with access", color="Limit type")
)

plotops <- list(theme_light(), facet_grid(IOU~., scales="fixed"), 
  # theme( axis.title=element_blank()),
  geom_line(aes(y=value, color=feature),linewidth=0.75), geom_point(aes(y=value, color=feature),size=1),
  scale_y_continuous(limits=c(0,1), breaks=c(0,0.2,0.4,0.6,0.8,1), labels=scales::percent_format(accuracy=1)),
  scale_x_continuous(breaks=c(0,as.numeric(at)), labels=c(">0", "1", "1.5","2","3","4","4.5","5","6","7","8","9","10")),
  scale_color_discrete_sequential(palette="Viridis", nmax=8, order=8:1),
  labs(x="Access threshold (kW)", y="Portion of vehicles with access", color="Household size"))
```

-----------------------------------
----------------------------------- EXPERIMENTAL CALCULATIONS ------------------

```{r}
#Preparing vehicle data 
LVL1_CHRG_PWR <- 1.5 #level 1 power
LVL2_CHRG_PWR <- 7.0 #level 2 power
NUM_VEH_CHRG <- 6.5   #from 6 to 7 vehicles per charging station, from Executive Orders B4818 and N7920.

IOU_vehwacc <- rbind(select(PGE_ICAaccess, GEOID, county, IOU, tothh_Cpoly, tothh_SU_Cpoly, tothh_duplex_Cpoly, tothh_3to4_Cpoly, tothh_5to9_Cpoly, tothh_10to19_Cpoly, tothh_20to49_Cpoly, tothh_50plus_Cpoly, ICL_kWphh, ICL_max_hhWt_nadj),
        select(SCE_ICAaccess, GEOID, county, IOU, tothh_Cpoly, tothh_SU_Cpoly, tothh_duplex_Cpoly, tothh_3to4_Cpoly, tothh_5to9_Cpoly, tothh_10to19_Cpoly, tothh_20to49_Cpoly, tothh_50plus_Cpoly, ICL_kWphh, ICL_max_hhWt_nadj)) %>%
  mutate(ICL_max_hhWt_nadj = if_else(IOU == "SCE", ICL_max_hhWt_nadj * 1000, ICL_max_hhWt_nadj))

IOU_vehwacc <- merge(IOU_vehwacc, ACS_bg_vehicles_hh[, c("GEOID", "avgveh_hh")], 
                     by = "GEOID", all.x = TRUE) %>%
  mutate(totveh_Cpoly = tothh_Cpoly*avgveh_hh) %>%
  mutate(totveh_SU_Cpoly = tothh_SU_Cpoly*avgveh_hh) %>%
  mutate(totveh_duplex_Cpoly = tothh_duplex_Cpoly*avgveh_hh) %>%
  mutate(totveh_3to4_Cpoly = tothh_3to4_Cpoly*avgveh_hh) %>%
  mutate(totveh_5to9_Cpoly = tothh_5to9_Cpoly*avgveh_hh) %>%
  mutate(totveh_10to19_Cpoly = tothh_10to19_Cpoly*avgveh_hh) %>%
  mutate(totveh_20to49_Cpoly = tothh_20to49_Cpoly*avgveh_hh) %>%
  mutate(totveh_50plus_Cpoly = tothh_50plus_Cpoly*avgveh_hh) %>%
  mutate(ICL_kWpveh = ICL_kWphh/avgveh_hh)
```

```{r}
 #SCENARIO 1.1
 #Individual charging
 #All households should have access to his individual charging infrastructure, either level 1 (1.5kW) or level 2 (7kW).
 IOU_vehwacc_sc11 <- IOU_vehwacc %>%
 mutate(Sc11_veh_load = tothh_Cpoly*LVL1_CHRG_PWR)%>%
  mutate(Sc11_veh_headroom = ICL_max_hhWt_nadj - Sc11_veh_load) %>%
  mutate(Sc11_vehwacc = ifelse(Sc11_veh_headroom>=0, totveh_Cpoly, totveh_Cpoly*ICL_max_hhWt_nadj/Sc11_veh_load))%>%
  mutate(Sc11_hhwacc = ifelse(Sc11_veh_headroom>=0, tothh_Cpoly, tothh_Cpoly*ICL_max_hhWt_nadj/Sc11_veh_load)) %>%
  mutate(Sc11_hhnoacc150 = ifelse(Sc11_veh_headroom >=-150 & Sc11_veh_headroom<0, tothh_Cpoly*(1-ICL_max_hhWt_nadj/Sc11_veh_load), 0))%>%
  mutate(Sc11_hhnoaccinf = ifelse(Sc11_veh_headroom < -150, tothh_Cpoly*(1-ICL_max_hhWt_nadj/Sc11_veh_load), 0))%>%
  mutate(Sc11_vehwacc_pct = Sc11_vehwacc/totveh_Cpoly)%>%
  mutate(Sc11_hhwacc_pct = Sc11_hhwacc/tothh_Cpoly)%>%
  mutate(Sc11_hhnoacc150_pct = Sc11_hhnoacc150/tothh_Cpoly)%>%
  mutate(Sc11_hhnoaccinf_pct = Sc11_hhnoaccinf/tothh_Cpoly)%>%
  #for all type of housing
  #vehicles with access
  mutate(Sc11_vehwacc_SU = Sc11_vehwacc_pct*totveh_SU_Cpoly)%>%
  mutate(Sc11_vehwacc_duplex = Sc11_vehwacc_pct*totveh_duplex_Cpoly)%>%
  mutate(Sc11_vehwacc_3to4 = Sc11_vehwacc_pct*totveh_3to4_Cpoly)%>%
  mutate(Sc11_vehwacc_5to9 = Sc11_vehwacc_pct*totveh_5to9_Cpoly)%>%
  mutate(Sc11_vehwacc_10to19 = Sc11_vehwacc_pct*totveh_10to19_Cpoly)%>%
  mutate(Sc11_vehwacc_20to49 = Sc11_vehwacc_pct*totveh_20to49_Cpoly)%>%
  mutate(Sc11_vehwacc_50plus = Sc11_vehwacc_pct*totveh_50plus_Cpoly)%>%
  #households with access
  mutate(Sc11_hhwacc_SU = Sc11_hhwacc_pct*tothh_SU_Cpoly)%>%
  mutate(Sc11_hhwacc_duplex = Sc11_hhwacc_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc11_hhwacc_3to4 = Sc11_hhwacc_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc11_hhwacc_5to9 = Sc11_hhwacc_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc11_hhwacc_10to19 = Sc11_hhwacc_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc11_hhwacc_20to49 = Sc11_hhwacc_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc11_hhwacc_50plus = Sc11_hhwacc_pct*tothh_50plus_Cpoly)%>%
  #households with no access - from -150kW to 0
  mutate(Sc11_hhnoacc150_SU = Sc11_hhnoacc150_pct*tothh_SU_Cpoly)%>%
  mutate(Sc11_hhnoacc150_duplex = Sc11_hhnoacc150_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc11_hhnoacc150_3to4 = Sc11_hhnoacc150_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc11_hhnoacc150_5to9 = Sc11_hhnoacc150_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc11_hhnoacc150_10to19 = Sc11_hhnoacc150_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc11_hhnoacc150_20to49 = Sc11_hhnoacc150_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc11_hhnoacc150_50plus = Sc11_hhnoacc150_pct*tothh_50plus_Cpoly)%>%
  #households with no access - more than -150kW
  mutate(Sc11_hhnoaccinf_SU = Sc11_hhnoaccinf_pct*tothh_SU_Cpoly)%>%
  mutate(Sc11_hhnoaccinf_duplex = Sc11_hhnoaccinf_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc11_hhnoaccinf_3to4 = Sc11_hhnoaccinf_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc11_hhnoaccinf_5to9 = Sc11_hhnoaccinf_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc11_hhnoaccinf_10to19 = Sc11_hhnoaccinf_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc11_hhnoaccinf_20to49 = Sc11_hhnoaccinf_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc11_hhnoaccinf_50plus = Sc11_hhnoaccinf_pct*tothh_50plus_Cpoly)

cat(" Scenario 1.1 - All households should have access to an individual level 1 (1.5 kW) charging facility.

    All: We estimate that ",sum(IOU_vehwacc_sc11$Sc11_vehwacc, na.rm = TRUE)," vehicles and ",sum(IOU_vehwacc_sc11$Sc11_hhwacc, na.rm = TRUE)," households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc11$Sc11_vehwacc, na.rm = TRUE)/sum(IOU_vehwacc_sc11$totveh_Cpoly, na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc11$Sc11_hhwacc, na.rm = TRUE)/sum(IOU_vehwacc_sc11$tothh_Cpoly, na.rm = TRUE)*100), "% of all households in PG&E and SCE service territory.
    
    PG&E: We estimate that ", sum(IOU_vehwacc_sc11$Sc11_vehwacc[IOU_vehwacc_sc11$IOU == "PGE"], na.rm = TRUE), "vehicles and ", sum(IOU_vehwacc_sc11$Sc11_hhwacc[IOU_vehwacc_sc11$IOU == "PGE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc11$Sc11_vehwacc[IOU_vehwacc_sc11$IOU == "PGE"], na.rm = TRUE)/sum(IOU_vehwacc_sc11$totveh_Cpoly[IOU_vehwacc_sc11$IOU == "PGE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc11$Sc11_hhwacc[IOU_vehwacc_sc11$IOU == "PGE"], na.rm = TRUE)/sum(IOU_vehwacc_sc11$tothh_Cpoly[IOU_vehwacc_sc11$IOU == "PGE"], na.rm = TRUE)*100), "% of all households in PG&E territory.

    SCE: We estimate that ", sum(IOU_vehwacc_sc11$Sc11_vehwacc[IOU_vehwacc_sc11$IOU == "SCE"], na.rm = TRUE), "vehicles and ", sum(IOU_vehwacc_sc11$Sc11_hhwacc[IOU_vehwacc_sc11$IOU == "SCE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc11$Sc11_vehwacc[IOU_vehwacc_sc11$IOU == "SCE"], na.rm = TRUE)/sum(IOU_vehwacc_sc11$totveh_Cpoly[IOU_vehwacc_sc11$IOU == "SCE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc11$Sc11_hhwacc[IOU_vehwacc_sc11$IOU == "SCE"], na.rm = TRUE)/sum(IOU_vehwacc_sc11$tothh_Cpoly[IOU_vehwacc_sc11$IOU == "SCE"], na.rm = TRUE)*100), "% of all households in SCE territory.")
```

```{r}
 #SCENARIO 1.2
 #Individual charging
 #All households should have access to his individual charging infrastructure, either level 1 (1.5kW) or level 2 (7kW).
 IOU_vehwacc_sc12 <- IOU_vehwacc %>%
 mutate(Sc12_veh_load = tothh_Cpoly*LVL2_CHRG_PWR)%>%
  mutate(Sc12_veh_headroom = ICL_max_hhWt_nadj - Sc12_veh_load) %>%
  mutate(Sc12_vehwacc = ifelse(Sc12_veh_headroom>=0, totveh_Cpoly, totveh_Cpoly*ICL_max_hhWt_nadj/Sc12_veh_load))%>%
  mutate(Sc12_hhwacc = ifelse(Sc12_veh_headroom>=0, tothh_Cpoly, tothh_Cpoly*ICL_max_hhWt_nadj/Sc12_veh_load)) %>%
  mutate(Sc12_hhnoacc150 = ifelse(Sc12_veh_headroom >=-150 & Sc12_veh_headroom<0, tothh_Cpoly*(1-ICL_max_hhWt_nadj/Sc12_veh_load), 0))%>%
  mutate(Sc12_hhnoaccinf = ifelse(Sc12_veh_headroom < -150, tothh_Cpoly*(1-ICL_max_hhWt_nadj/Sc12_veh_load), 0))%>%
  mutate(Sc12_vehwacc_pct = Sc12_vehwacc/totveh_Cpoly)%>%
  mutate(Sc12_hhwacc_pct = Sc12_hhwacc/tothh_Cpoly)%>%
  mutate(Sc12_hhnoacc150_pct = Sc12_hhnoacc150/tothh_Cpoly)%>%
  mutate(Sc12_hhnoaccinf_pct = Sc12_hhnoaccinf/tothh_Cpoly)%>%
  #for all type of housing
  #vehicles with access
  mutate(Sc12_vehwacc_SU = Sc12_vehwacc_pct*totveh_SU_Cpoly)%>%
  mutate(Sc12_vehwacc_duplex = Sc12_vehwacc_pct*totveh_duplex_Cpoly)%>%
  mutate(Sc12_vehwacc_3to4 = Sc12_vehwacc_pct*totveh_3to4_Cpoly)%>%
  mutate(Sc12_vehwacc_5to9 = Sc12_vehwacc_pct*totveh_5to9_Cpoly)%>%
  mutate(Sc12_vehwacc_10to19 = Sc12_vehwacc_pct*totveh_10to19_Cpoly)%>%
  mutate(Sc12_vehwacc_20to49 = Sc12_vehwacc_pct*totveh_20to49_Cpoly)%>%
  mutate(Sc12_vehwacc_50plus = Sc12_vehwacc_pct*totveh_50plus_Cpoly)%>%
  #households with access
  mutate(Sc12_hhwacc_SU = Sc12_hhwacc_pct*tothh_SU_Cpoly)%>%
  mutate(Sc12_hhwacc_duplex = Sc12_hhwacc_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc12_hhwacc_3to4 = Sc12_hhwacc_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc12_hhwacc_5to9 = Sc12_hhwacc_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc12_hhwacc_10to19 = Sc12_hhwacc_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc12_hhwacc_20to49 = Sc12_hhwacc_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc12_hhwacc_50plus = Sc12_hhwacc_pct*tothh_50plus_Cpoly)%>%
  #households with no access - from -150kW to 0
  mutate(Sc12_hhnoacc150_SU = Sc12_hhnoacc150_pct*tothh_SU_Cpoly)%>%
  mutate(Sc12_hhnoacc150_duplex = Sc12_hhnoacc150_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc12_hhnoacc150_3to4 = Sc12_hhnoacc150_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc12_hhnoacc150_5to9 = Sc12_hhnoacc150_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc12_hhnoacc150_10to19 = Sc12_hhnoacc150_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc12_hhnoacc150_20to49 = Sc12_hhnoacc150_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc12_hhnoacc150_50plus = Sc12_hhnoacc150_pct*tothh_50plus_Cpoly)%>%
  #households with no access - more than -150kW
  mutate(Sc12_hhnoaccinf_SU = Sc12_hhnoaccinf_pct*tothh_SU_Cpoly)%>%
  mutate(Sc12_hhnoaccinf_duplex = Sc12_hhnoaccinf_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc12_hhnoaccinf_3to4 = Sc12_hhnoaccinf_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc12_hhnoaccinf_5to9 = Sc12_hhnoaccinf_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc12_hhnoaccinf_10to19 = Sc12_hhnoaccinf_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc12_hhnoaccinf_20to49 = Sc12_hhnoaccinf_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc12_hhnoaccinf_50plus = Sc12_hhnoaccinf_pct*tothh_50plus_Cpoly)

cat(" Scenario 1.2 - All households should have access to an individual level 2 (7 kW) charging facility.

    All: We estimate that ",sum(IOU_vehwacc_sc12$Sc12_vehwacc, na.rm = TRUE)," vehicles and ",sum(IOU_vehwacc_sc12$Sc12_hhwacc, na.rm = TRUE)," households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc12$Sc12_vehwacc, na.rm = TRUE)/sum(IOU_vehwacc_sc12$totveh_Cpoly, na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc12$Sc12_hhwacc, na.rm = TRUE)/sum(IOU_vehwacc_sc12$tothh_Cpoly, na.rm = TRUE)*100), "% of all households in PG&E and SCE service territory.
    
    PG&E: We estimate that ", sum(IOU_vehwacc_sc12$Sc12_vehwacc[IOU_vehwacc_sc12$IOU == "PGE"], na.rm = TRUE), "vehicles and ", sum(IOU_vehwacc_sc12$Sc12_hhwacc[IOU_vehwacc_sc12$IOU == "PGE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc12$Sc12_vehwacc[IOU_vehwacc_sc12$IOU == "PGE"], na.rm = TRUE)/sum(IOU_vehwacc_sc12$totveh_Cpoly[IOU_vehwacc_sc12$IOU == "PGE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc12$Sc12_hhwacc[IOU_vehwacc_sc12$IOU == "PGE"], na.rm = TRUE)/sum(IOU_vehwacc_sc12$tothh_Cpoly[IOU_vehwacc_sc12$IOU == "PGE"], na.rm = TRUE)*100), "% of all households in PG&E territory.

    SCE: We estimate that ", sum(IOU_vehwacc_sc12$Sc12_vehwacc[IOU_vehwacc_sc12$IOU == "SCE"], na.rm = TRUE), "vehicles and ", sum(IOU_vehwacc_sc12$Sc12_hhwacc[IOU_vehwacc_sc12$IOU == "SCE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc12$Sc12_vehwacc[IOU_vehwacc_sc12$IOU == "SCE"], na.rm = TRUE)/sum(IOU_vehwacc_sc12$totveh_Cpoly[IOU_vehwacc_sc12$IOU == "SCE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc12$Sc12_hhwacc[IOU_vehwacc_sc12$IOU == "SCE"], na.rm = TRUE)/sum(IOU_vehwacc_sc12$tothh_Cpoly[IOU_vehwacc_sc12$IOU == "SCE"], na.rm = TRUE)*100), "% of all households in SCE territory.")
```

```{r}
#SCENARIO 2
#Shared charging only
IOU_vehwacc_sc2 <- IOU_vehwacc %>%
  mutate(Sc2_veh_load = totveh_Cpoly/NUM_VEH_CHRG*LVL2_CHRG_PWR)%>%
  mutate(Sc2_veh_headroom = ICL_max_hhWt_nadj - Sc2_veh_load)%>%
  mutate(Sc2_vehwacc = ifelse(Sc2_veh_headroom>=0, totveh_Cpoly, totveh_Cpoly*ICL_max_hhWt_nadj/Sc2_veh_load))%>%
  mutate(Sc2_hhwacc = ifelse(Sc2_veh_headroom>=0, tothh_Cpoly, tothh_Cpoly*ICL_max_hhWt_nadj/Sc2_veh_load))%>%
  mutate(Sc2_hhnoacc150 = ifelse(Sc2_veh_headroom >=-150 & Sc2_veh_headroom<0, tothh_Cpoly*(1-ICL_max_hhWt_nadj/Sc2_veh_load), 0))%>%
  mutate(Sc2_hhnoaccinf = ifelse(Sc2_veh_headroom < -150, tothh_Cpoly*(1-ICL_max_hhWt_nadj/Sc2_veh_load), 0))%>%
  mutate(Sc2_vehwacc_pct = Sc2_vehwacc/totveh_Cpoly)%>%
  mutate(Sc2_hhwacc_pct = Sc2_hhwacc/tothh_Cpoly)%>%
  mutate(Sc2_hhnoacc150_pct = Sc2_hhnoacc150/tothh_Cpoly)%>%
  mutate(Sc2_hhnoaccinf_pct = Sc2_hhnoaccinf/tothh_Cpoly)%>%
  #for all type of housing
  #vehicles with access
  mutate(Sc2_vehwacc_SU = Sc2_vehwacc_pct*totveh_SU_Cpoly)%>%
  mutate(Sc2_vehwacc_duplex = Sc2_vehwacc_pct*totveh_duplex_Cpoly)%>%
  mutate(Sc2_vehwacc_3to4 = Sc2_vehwacc_pct*totveh_3to4_Cpoly)%>%
  mutate(Sc2_vehwacc_5to9 = Sc2_vehwacc_pct*totveh_5to9_Cpoly)%>%
  mutate(Sc2_vehwacc_10to19 = Sc2_vehwacc_pct*totveh_10to19_Cpoly)%>%
  mutate(Sc2_vehwacc_20to49 = Sc2_vehwacc_pct*totveh_20to49_Cpoly)%>%
  mutate(Sc2_vehwacc_50plus = Sc2_vehwacc_pct*totveh_50plus_Cpoly)%>%
  #households with access
  mutate(Sc2_hhwacc_SU = Sc2_hhwacc_pct*tothh_SU_Cpoly)%>%
  mutate(Sc2_hhwacc_duplex = Sc2_hhwacc_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc2_hhwacc_3to4 = Sc2_hhwacc_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc2_hhwacc_5to9 = Sc2_hhwacc_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc2_hhwacc_10to19 = Sc2_hhwacc_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc2_hhwacc_20to49 = Sc2_hhwacc_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc2_hhwacc_50plus = Sc2_hhwacc_pct*tothh_50plus_Cpoly)%>%
  #households with no access - from -150kW to 0
  mutate(Sc2_hhnoacc150_SU = Sc2_hhnoacc150_pct*tothh_SU_Cpoly)%>%
  mutate(Sc2_hhnoacc150_duplex = Sc2_hhnoacc150_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc2_hhnoacc150_3to4 = Sc2_hhnoacc150_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc2_hhnoacc150_5to9 = Sc2_hhnoacc150_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc2_hhnoacc150_10to19 = Sc2_hhnoacc150_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc2_hhnoacc150_20to49 = Sc2_hhnoacc150_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc2_hhnoacc150_50plus = Sc2_hhnoacc150_pct*tothh_50plus_Cpoly)%>%
  #households with no access - more than -150kW
  mutate(Sc2_hhnoaccinf_SU = Sc2_hhnoaccinf_pct*tothh_SU_Cpoly)%>%
  mutate(Sc2_hhnoaccinf_duplex = Sc2_hhnoaccinf_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc2_hhnoaccinf_3to4 = Sc2_hhnoaccinf_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc2_hhnoaccinf_5to9 = Sc2_hhnoaccinf_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc2_hhnoaccinf_10to19 = Sc2_hhnoaccinf_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc2_hhnoaccinf_20to49 = Sc2_hhnoaccinf_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc2_hhnoaccinf_50plus = Sc2_hhnoaccinf_pct*tothh_50plus_Cpoly)

cat(" Scenario 2 - All households should have access to level 2 (7.0 kW) charging facilities close to their homes. One charging infrastructure can support the load of 6.5 vehicles.

    All: We estimate that ",sum(IOU_vehwacc_sc2$Sc2_vehwacc, na.rm = TRUE)," vehicles and ",sum(IOU_vehwacc_sc2$Sc2_hhwacc, na.rm = TRUE)," households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc2$Sc2_vehwacc, na.rm = TRUE)/sum(IOU_vehwacc_sc2$totveh_Cpoly, na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc2$Sc2_hhwacc, na.rm = TRUE)/sum(IOU_vehwacc_sc2$tothh_Cpoly, na.rm = TRUE)*100), "% of all households in PG&E and SCE service territory.
    
    PG&E: We estimate that ", sum(IOU_vehwacc_sc2$Sc2_vehwacc[IOU_vehwacc_sc2$IOU == "PGE"], na.rm = TRUE), "vehicles and ", sum(IOU_vehwacc_sc2$Sc2_hhwacc[IOU_vehwacc_sc2$IOU == "PGE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc2$Sc2_vehwacc[IOU_vehwacc_sc2$IOU == "PGE"], na.rm = TRUE)/sum(IOU_vehwacc_sc2$totveh_Cpoly[IOU_vehwacc_sc2$IOU == "PGE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc2$Sc2_hhwacc[IOU_vehwacc_sc2$IOU == "PGE"], na.rm = TRUE)/sum(IOU_vehwacc_sc2$tothh_Cpoly[IOU_vehwacc_sc2$IOU == "PGE"], na.rm = TRUE)*100), "% of all households in PG&E territory.

    SCE: We estimate that ", sum(IOU_vehwacc_sc2$Sc2_vehwacc[IOU_vehwacc_sc2$IOU == "SCE"], na.rm = TRUE), "vehicles and ", sum(IOU_vehwacc_sc2$Sc2_hhwacc[IOU_vehwacc_sc2$IOU == "SCE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc2$Sc2_vehwacc[IOU_vehwacc_sc2$IOU == "SCE"], na.rm = TRUE)/sum(IOU_vehwacc_sc2$totveh_Cpoly[IOU_vehwacc_sc2$IOU == "SCE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc2$Sc2_hhwacc[IOU_vehwacc_sc2$IOU == "SCE"], na.rm = TRUE)/sum(IOU_vehwacc_sc2$tothh_Cpoly[IOU_vehwacc_sc2$IOU == "SCE"], na.rm = TRUE)*100), "% of all households in SCE territory.")
```

```{r}
#SCENARIO 3
#Mixed charging - per type of housing
#SU --> 1.5kW charging station/hh
#Duplex --> 1/2 * 7.0kW charging station/hh
#3to4 --> 1/3.5 * 7.0kW charging station/hh
#5to9 --> 6.5 veh/charging station
#[...]
#50plus --> 6.5veh/charging station

IOU_vehwacc_sc3 <- IOU_vehwacc %>%
  mutate(Sc3_veh_load = tothh_SU_Cpoly*LVL1_CHRG_PWR + tothh_duplex_Cpoly/2*LVL2_CHRG_PWR + tothh_3to4_Cpoly/3.5*LVL2_CHRG_PWR + (totveh_5to9_Cpoly+totveh_10to19_Cpoly+totveh_20to49_Cpoly+totveh_50plus_Cpoly)/NUM_VEH_CHRG*LVL2_CHRG_PWR )%>%
  mutate(Sc3_veh_headroom = ICL_max_hhWt_nadj - Sc3_veh_load) %>%
  mutate(Sc3_vehwacc = ifelse(Sc3_veh_headroom>=0, totveh_Cpoly, totveh_Cpoly*ICL_max_hhWt_nadj/Sc3_veh_load))%>%
  mutate(Sc3_hhwacc = ifelse(Sc3_veh_headroom>=0, tothh_Cpoly, tothh_Cpoly*ICL_max_hhWt_nadj/Sc3_veh_load)) %>%
  mutate(Sc3_hhnoacc150 = ifelse(Sc3_veh_headroom >=-150 & Sc3_veh_headroom<0, tothh_Cpoly*(1-ICL_max_hhWt_nadj/Sc3_veh_load), 0))%>%
  mutate(Sc3_hhnoaccinf = ifelse(Sc3_veh_headroom < -150, tothh_Cpoly*(1-ICL_max_hhWt_nadj/Sc3_veh_load), 0))%>%
  mutate(Sc3_vehwacc_pct = Sc3_vehwacc/totveh_Cpoly)%>%
  mutate(Sc3_hhwacc_pct = Sc3_hhwacc/tothh_Cpoly)%>%
  mutate(Sc3_hhnoacc150_pct = Sc3_hhnoacc150/tothh_Cpoly)%>%
  mutate(Sc3_hhnoaccinf_pct = Sc3_hhnoaccinf/tothh_Cpoly)%>%
  #for all type of housing
  #vehicles with access
  mutate(Sc3_vehwacc_SU = Sc3_vehwacc_pct*totveh_SU_Cpoly)%>%
  mutate(Sc3_vehwacc_duplex = Sc3_vehwacc_pct*totveh_duplex_Cpoly)%>%
  mutate(Sc3_vehwacc_3to4 = Sc3_vehwacc_pct*totveh_3to4_Cpoly)%>%
  mutate(Sc3_vehwacc_5to9 = Sc3_vehwacc_pct*totveh_5to9_Cpoly)%>%
  mutate(Sc3_vehwacc_10to19 = Sc3_vehwacc_pct*totveh_10to19_Cpoly)%>%
  mutate(Sc3_vehwacc_20to49 = Sc3_vehwacc_pct*totveh_20to49_Cpoly)%>%
  mutate(Sc3_vehwacc_50plus = Sc3_vehwacc_pct*totveh_50plus_Cpoly)%>%
  #households with access
  mutate(Sc3_hhwacc_SU = Sc3_hhwacc_pct*tothh_SU_Cpoly)%>%
  mutate(Sc3_hhwacc_duplex = Sc3_hhwacc_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc3_hhwacc_3to4 = Sc3_hhwacc_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc3_hhwacc_5to9 = Sc3_hhwacc_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc3_hhwacc_10to19 = Sc3_hhwacc_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc3_hhwacc_20to49 = Sc3_hhwacc_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc3_hhwacc_50plus = Sc3_hhwacc_pct*tothh_50plus_Cpoly)%>%
  #households with no access - from -150kW to 0
  mutate(Sc3_hhnoacc150_SU = Sc3_hhnoacc150_pct*tothh_SU_Cpoly)%>%
  mutate(Sc3_hhnoacc150_duplex = Sc3_hhnoacc150_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc3_hhnoacc150_3to4 = Sc3_hhnoacc150_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc3_hhnoacc150_5to9 = Sc3_hhnoacc150_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc3_hhnoacc150_10to19 = Sc3_hhnoacc150_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc3_hhnoacc150_20to49 = Sc3_hhnoacc150_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc3_hhnoacc150_50plus = Sc3_hhnoacc150_pct*tothh_50plus_Cpoly)%>%
  #households with no access - more than -150kW
  mutate(Sc3_hhnoaccinf_SU = Sc3_hhnoaccinf_pct*tothh_SU_Cpoly)%>%
  mutate(Sc3_hhnoaccinf_duplex = Sc3_hhnoaccinf_pct*tothh_duplex_Cpoly)%>%
  mutate(Sc3_hhnoaccinf_3to4 = Sc3_hhnoaccinf_pct*tothh_3to4_Cpoly)%>%
  mutate(Sc3_hhnoaccinf_5to9 = Sc3_hhnoaccinf_pct*tothh_5to9_Cpoly)%>%
  mutate(Sc3_hhnoaccinf_10to19 = Sc3_hhnoaccinf_pct*tothh_10to19_Cpoly)%>%
  mutate(Sc3_hhnoaccinf_20to49 = Sc3_hhnoaccinf_pct*tothh_20to49_Cpoly)%>%
  mutate(Sc3_hhnoaccinf_50plus = Sc3_hhnoaccinf_pct*tothh_50plus_Cpoly)

cat(" Scenario 3 - All households should have access to home charging. Single unit houses have access to level 1 charging (1.5 kW) and MUDs to level 2. The number of charging stations depends on the housing types (see above).
    All: We estimate that ",sum(IOU_vehwacc_sc3$totveh_Cpoly[IOU_vehwacc_sc3$Sc3_veh_headroom >= 0], na.rm = TRUE)," vehicles and ",sum(IOU_vehwacc_sc3$tothh_Cpoly[IOU_vehwacc_sc3$Sc3_veh_headroom >= 0], na.rm = TRUE)," households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc3$totveh_Cpoly[IOU_vehwacc_sc3$Sc3_veh_headroom >= 0], na.rm = TRUE)/sum(IOU_vehwacc_sc3$totveh_Cpoly, na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc3$tothh_Cpoly[IOU_vehwacc_sc3$Sc3_veh_headroom >= 0], na.rm = TRUE)/sum(IOU_vehwacc_sc3$tothh_Cpoly, na.rm = TRUE)*100), "% of all households in PG&E and SCE service territory.

    PG&E: We estimate that ", sum(IOU_vehwacc_sc3$Sc3_vehwacc[IOU_vehwacc_sc3$IOU == "PGE"], na.rm = TRUE), "vehicles and ", sum(IOU_vehwacc_sc3$Sc3_hhwacc[IOU_vehwacc_sc3$IOU == "PGE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc3$Sc3_vehwacc[IOU_vehwacc_sc3$IOU == "PGE"], na.rm = TRUE)/sum(IOU_vehwacc_sc3$totveh_Cpoly[IOU_vehwacc_sc3$IOU == "PGE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc3$Sc3_hhwacc[IOU_vehwacc_sc3$IOU == "PGE"], na.rm = TRUE)/sum(IOU_vehwacc_sc3$tothh_Cpoly[IOU_vehwacc_sc3$IOU == "PGE"], na.rm = TRUE)*100), "% of all households in PG&E territory.

    SCE: We estimate that ", sum(IOU_vehwacc_sc3$Sc3_vehwacc[IOU_vehwacc_sc3$IOU == "SCE"], na.rm = TRUE), "vehicles and ", sum(IOU_vehwacc_sc3$Sc3_hhwacc[IOU_vehwacc_sc3$IOU == "SCE"], na.rm = TRUE), "households have access to an adequate grid for charging.
    It represents aprox. ", round(sum(IOU_vehwacc_sc3$Sc3_vehwacc[IOU_vehwacc_sc3$IOU == "SCE"], na.rm = TRUE)/sum(IOU_vehwacc_sc3$totveh_Cpoly[IOU_vehwacc_sc3$IOU == "SCE"], na.rm = TRUE)*100), "% of all vehicles and ", round(sum(IOU_vehwacc_sc3$Sc3_hhwacc[IOU_vehwacc_sc3$IOU == "SCE"], na.rm = TRUE)/sum(IOU_vehwacc_sc3$tothh_Cpoly[IOU_vehwacc_sc3$IOU == "SCE"], na.rm = TRUE)*100), "% of all households in SCE territory.")
```

```{r}
#Comparison between Scenarios
#Scenario 1.1
df_sc11_hh <- select(IOU_vehwacc_sc11, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("Sc11_hhwacc"), starts_with("Sc11_hhnoacc")) %>%
  group_by(IOU) %>%
  summarise(
    # tothh = sum(tothh_Cpoly, na.rm=TRUE),
            Sc11_wacc_all_pct = sum(Sc11_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc11_wacc_SU_pct = sum(Sc11_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc11_wacc_duplex_pct = sum(Sc11_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc11_wacc_3to4_pct = sum(Sc11_hhwacc_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc11_wacc_5to9_pct = sum(Sc11_hhwacc_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc11_wacc_10to19_pct = sum(Sc11_hhwacc_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc11_wacc_20to49_pct = sum(Sc11_hhwacc_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc11_wacc_50plus_pct = sum(Sc11_hhwacc_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE),
            Sc11_noacc150_all_pct = sum(Sc11_hhnoacc150, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc11_noacc150_SU_pct = sum(Sc11_hhnoacc150_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc11_noacc150_duplex_pct = sum(Sc11_hhnoacc150_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc11_noacc150_3to4_pct = sum(Sc11_hhnoacc150_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc11_noacc150_5to9_pct = sum(Sc11_hhnoacc150_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc11_noacc150_10to19_pct = sum(Sc11_hhnoacc150_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc11_noacc150_20to49_pct = sum(Sc11_hhnoacc150_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc11_noacc150_50plus_pct = sum(Sc11_hhnoacc150_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE),
            Sc11_noaccinf_all_pct = sum(Sc11_hhnoaccinf, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc11_noaccinf_SU_pct = sum(Sc11_hhnoaccinf_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc11_noaccinf_duplex_pct = sum(Sc11_hhnoaccinf_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc11_noaccinf_3to4_pct = sum(Sc11_hhnoaccinf_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc11_noaccinf_5to9_pct = sum(Sc11_hhnoaccinf_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc11_noaccinf_10to19_pct = sum(Sc11_hhnoaccinf_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc11_noaccinf_20to49_pct = sum(Sc11_hhnoaccinf_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc11_noaccinf_50plus_pct = sum(Sc11_hhnoaccinf_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE))

#Scenario 1.2
df_sc12_hh <- select(IOU_vehwacc_sc12, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("Sc12_hhwacc"), starts_with("Sc12_hhnoacc")) %>%
  group_by(IOU) %>%
  summarise(
    # tothh = sum(tothh_Cpoly, na.rm=TRUE),
            Sc12_wacc_all_pct = sum(Sc12_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc12_wacc_SU_pct = sum(Sc12_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc12_wacc_duplex_pct = sum(Sc12_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc12_wacc_3to4_pct = sum(Sc12_hhwacc_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc12_wacc_5to9_pct = sum(Sc12_hhwacc_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc12_wacc_10to19_pct = sum(Sc12_hhwacc_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc12_wacc_20to49_pct = sum(Sc12_hhwacc_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc12_wacc_50plus_pct = sum(Sc12_hhwacc_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE),
            Sc12_noacc150_all_pct = sum(Sc12_hhnoacc150, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc12_noacc150_SU_pct = sum(Sc12_hhnoacc150_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc12_noacc150_duplex_pct = sum(Sc12_hhnoacc150_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc12_noacc150_3to4_pct = sum(Sc12_hhnoacc150_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc12_noacc150_5to9_pct = sum(Sc12_hhnoacc150_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc12_noacc150_10to19_pct = sum(Sc12_hhnoacc150_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc12_noacc150_20to49_pct = sum(Sc12_hhnoacc150_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc12_noacc150_50plus_pct = sum(Sc12_hhnoacc150_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE),
            Sc12_noaccinf_all_pct = sum(Sc12_hhnoaccinf, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc12_noaccinf_SU_pct = sum(Sc12_hhnoaccinf_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc12_noaccinf_duplex_pct = sum(Sc12_hhnoaccinf_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc12_noaccinf_3to4_pct = sum(Sc12_hhnoaccinf_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc12_noaccinf_5to9_pct = sum(Sc12_hhnoaccinf_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc12_noaccinf_10to19_pct = sum(Sc12_hhnoaccinf_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc12_noaccinf_20to49_pct = sum(Sc12_hhnoaccinf_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc12_noaccinf_50plus_pct = sum(Sc12_hhnoaccinf_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE))

#Scenario 2
df_sc2_hh <- select(IOU_vehwacc_sc2, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("Sc2_hhwacc"), starts_with("Sc2_hhnoacc")) %>%
  group_by(IOU) %>%
  summarise(
    # tothh = sum(tothh_Cpoly, na.rm=TRUE),
            Sc2_wacc_all_pct = sum(Sc2_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc2_wacc_SU_pct = sum(Sc2_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc2_wacc_duplex_pct = sum(Sc2_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc2_wacc_3to4_pct = sum(Sc2_hhwacc_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc2_wacc_5to9_pct = sum(Sc2_hhwacc_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc2_wacc_10to19_pct = sum(Sc2_hhwacc_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc2_wacc_20to49_pct = sum(Sc2_hhwacc_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc2_wacc_50plus_pct = sum(Sc2_hhwacc_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE),
            Sc2_noacc150_all_pct = sum(Sc2_hhnoacc150, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc2_noacc150_SU_pct = sum(Sc2_hhnoacc150_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc2_noacc150_duplex_pct = sum(Sc2_hhnoacc150_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc2_noacc150_3to4_pct = sum(Sc2_hhnoacc150_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc2_noacc150_5to9_pct = sum(Sc2_hhnoacc150_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc2_noacc150_10to19_pct = sum(Sc2_hhnoacc150_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc2_noacc150_20to49_pct = sum(Sc2_hhnoacc150_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc2_noacc150_50plus_pct = sum(Sc2_hhnoacc150_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE),
            Sc2_noaccinf_all_pct = sum(Sc2_hhnoaccinf, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc2_noaccinf_SU_pct = sum(Sc2_hhnoaccinf_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc2_noaccinf_duplex_pct = sum(Sc2_hhnoaccinf_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc2_noaccinf_3to4_pct = sum(Sc2_hhnoaccinf_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc2_noaccinf_5to9_pct = sum(Sc2_hhnoaccinf_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc2_noaccinf_10to19_pct = sum(Sc2_hhnoaccinf_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc2_noaccinf_20to49_pct = sum(Sc2_hhnoaccinf_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc2_noaccinf_50plus_pct = sum(Sc2_hhnoaccinf_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE))

#Scenario 3
df_sc3_hh <- select(IOU_vehwacc_sc3, GEOID, county, IOU, tothh_Cpoly, intersect(starts_with("tothh_"), ends_with("_Cpoly")), starts_with("Sc3_hhwacc"), starts_with("Sc3_hhnoacc")) %>%
  group_by(IOU) %>%
  summarise(
    # tothh = sum(tothh_Cpoly, na.rm=TRUE),
            Sc3_wacc_all_pct = sum(Sc3_hhwacc, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc3_wacc_SU_pct = sum(Sc3_hhwacc_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc3_wacc_duplex_pct = sum(Sc3_hhwacc_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc3_wacc_3to4_pct = sum(Sc3_hhwacc_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc3_wacc_5to9_pct = sum(Sc3_hhwacc_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc3_wacc_10to19_pct = sum(Sc3_hhwacc_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc3_wacc_20to49_pct = sum(Sc3_hhwacc_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc3_wacc_50plus_pct = sum(Sc3_hhwacc_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE),
            Sc3_noacc150_all_pct = sum(Sc3_hhnoacc150, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc3_noacc150_SU_pct = sum(Sc3_hhnoacc150_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc3_noacc150_duplex_pct = sum(Sc3_hhnoacc150_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc3_noacc150_3to4_pct = sum(Sc3_hhnoacc150_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc3_noacc150_5to9_pct = sum(Sc3_hhnoacc150_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc3_noacc150_10to19_pct = sum(Sc3_hhnoacc150_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc3_noacc150_20to49_pct = sum(Sc3_hhnoacc150_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc3_noacc150_50plus_pct = sum(Sc3_hhnoacc150_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE),
            Sc3_noaccinf_all_pct = sum(Sc3_hhnoaccinf, na.rm=TRUE)/sum(tothh_Cpoly, na.rm=TRUE),
            Sc3_noaccinf_SU_pct = sum(Sc3_hhnoaccinf_SU, na.rm=TRUE)/sum(tothh_SU_Cpoly, na.rm=TRUE),
            Sc3_noaccinf_duplex_pct = sum(Sc3_hhnoaccinf_duplex, na.rm=TRUE)/sum(tothh_duplex_Cpoly, na.rm=TRUE),
            Sc3_noaccinf_3to4_pct = sum(Sc3_hhnoaccinf_3to4, na.rm=TRUE)/sum(tothh_3to4_Cpoly, na.rm=TRUE),
            Sc3_noaccinf_5to9_pct = sum(Sc3_hhnoaccinf_5to9, na.rm=TRUE)/sum(tothh_5to9_Cpoly, na.rm=TRUE),
            Sc3_noaccinf_10to19_pct = sum(Sc3_hhnoaccinf_10to19, na.rm=TRUE)/sum(tothh_10to19_Cpoly, na.rm=TRUE),
            Sc3_noaccinf_20to49_pct = sum(Sc3_hhnoaccinf_20to49, na.rm=TRUE)/sum(tothh_20to49_Cpoly, na.rm=TRUE),
            Sc3_noaccinf_50plus_pct = sum(Sc3_hhnoaccinf_50plus, na.rm=TRUE)/sum(tothh_50plus_Cpoly, na.rm=TRUE))

transform_df <- function(df) {
  df %>%
    pivot_longer(
      cols = -IOU,
      names_to = c("Scenario", "Load", "Housing", ".value"),
      names_sep = "_",
      values_to = "Value"
    )
}

df_plot <- bind_rows(
  transform_df(df_sc11_hh),
  transform_df(df_sc12_hh),
  transform_df(df_sc2_hh),
  transform_df(df_sc3_hh)
)

df_plot$Housing <- recode(factor(df_plot$Housing, levels = c(
  "all", "SU", "duplex", "3to4", "5to9", "10to19", "20to49", "50plus")),
  "all"= "All", "SU" = "Single Unit", "duplex" = "Duplex",
  "3to4" = "3-4 units", "5to9" = "5-9 units", "10to19" = "10-19 units",
  "20to49" = "20-49 units", "50plus" = ">50 units"
)

df_plot$Scenario <- recode(factor(df_plot$Scenario, levels = c(
  "Sc11", "Sc12", "Sc2", "Sc3")),
  "Sc11"= "Sc.1 - Individual access (1.5kW)", "Sc12"= "Sc.1 - Individual access (7.0kW)", "Sc2"= "Sc.2 - Shared access", "Sc3" = "Sc.3 - Mixed"
)

df_plot$Load <- recode(factor(df_plot$Load, levels = c(
  "wacc", "noacc150", "noaccinf")),
  "wacc"= "Have access", "noacc150" = "[0-150kW]", "noaccinf" = "[+150kW]"
)
```

```{r}
#Plot Access
df_plot_access = subset(df_plot, Load == "Have access")

plot_access <- ggplot(df_plot_access, aes(x = Housing, y = pct, color = Scenario)) +
  facet_grid(~ IOU, scales = "free_x", space = "free_x") +
  geom_point(size = 2) +
  scale_color_manual(values = c("#7EE081", "#62A87C", "#00487C", "#F6F5AE")) +  # Adjust colors as needed
  labs(title = "Proportion of households with access",
       x = "Housing Type",
       y = "Proportion of households [%]",
       # shape = "Access / No Access",
       color = "Scenario") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), labels = scales::percent_format(accuracy = 1))

#Plot No access
df_plot_no_access = subset(df_plot, Load != "Have access")

plot_no_access <- ggplot(df_plot_no_access, aes(x = Housing, y = pct, shape = Load, color = Scenario)) +
  facet_grid(~ IOU, scales = "free_x", space = "free_x") +
  geom_point(size = 2) +
  scale_shape_manual(values = c(15, 17)) +
  scale_color_manual(values = c("#7EE081", "#62A87C", "#00487C", "#F6F5AE")) +  # Adjust colors as needed
  labs(title = "Proportion of households without access",
       x = "Housing Type",
       y = "Proportion of households [%]",
       shape = "Lack of power",
       color = "Scenario") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), labels = scales::percent_format(accuracy = 1))

combined_plot <- grid.arrange(plot_access, plot_no_access, ncol = 1)
ggsave("figures/access/vehicles/IOU_access_scenarios.png", combined_plot, width = 6.5, height = 7.5)


```

-----------------------------------
-----------------------------------

ACCESS
We calculate the number of households with access based on grid limits.

```{r}
SCE_ICAaccess[["hhwacc_0_ICL_pct"]] <- ifelse(SCE_ICAaccess[["ICL_kWphh"]]>0, 1, 0)
PGE_ICAaccess[["hhwacc_0_ICL_pct"]] <- ifelse(PGE_ICAaccess[["ICL_kWphh"]]>0, 1, 0)

for (t in 1:length(at)) { 
  name <- paste0("hhwacc_",at[t],"_ICL_pct") 
  
  SCE_ICAaccess[[name]] <- ifelse(SCE_ICAaccess[["ICL_kWphh"]]>=as.numeric(at[t]), 1, SCE_ICAaccess[["ICL_kWphh"]]/as.numeric(at[t]))
  SCE_ICAaccess[[paste0("hhwacc_",at[t],"_ICL")]] <- SCE_ICAaccess[[name]]*SCE_ICAaccess$tothh_Cpoly
  
  PGE_ICAaccess[[name]] <- ifelse(PGE_ICAaccess[["ICL_kWphh"]]>=as.numeric(at[t]), 1, PGE_ICAaccess[["ICL_kWphh"]]/as.numeric(at[t]))
  PGE_ICAaccess[[paste0("hhwacc_",at[t],"_ICL")]] <- PGE_ICAaccess[[name]]*PGE_ICAaccess$tothh_Cpoly
}
```

```{r} 
###Computing number of households with access per block groups
IOU_ICAaccess_grid <- 
  rbind(select(PGE_ICAaccess, GEOID, IOU, tothh_Cpoly, tothh_SU_Cpoly, tothh_duplex_Cpoly, tothh_3to4_Cpoly, tothh_5to9_Cpoly, tothh_10to19_Cpoly, tothh_20to49_Cpoly, tothh_50plus_Cpoly, intersect(starts_with("hhwacc_"), ends_with("_pct"))),
        select(SCE_ICAaccess, GEOID, IOU, tothh_Cpoly, tothh_SU_Cpoly, tothh_duplex_Cpoly, tothh_3to4_Cpoly, tothh_5to9_Cpoly, tothh_10to19_Cpoly, tothh_20to49_Cpoly, tothh_50plus_Cpoly, intersect(starts_with("hhwacc_"), ends_with("_pct"))))

IOU_ICAaccess_grid <- merge(IOU_ICAaccess_grid, ACS_bg_vehicles_hh[, c("GEOID", "avgveh_hh")], 
                     by = "GEOID", all.x = TRUE) %>%
  melt(id=c("IOU", "tothh_Cpoly", "avgveh_hh", "GEOID", "tothh_SU_Cpoly", "tothh_duplex_Cpoly", "tothh_3to4_Cpoly", "tothh_5to9_Cpoly", "tothh_10to19_Cpoly", "tothh_20to49_Cpoly", "tothh_50plus_Cpoly")) %>%
  mutate(totveh_Cpoly = tothh_Cpoly*avgveh_hh) %>%
  mutate(totveh_SU_Cpoly = tothh_SU_Cpoly*avgveh_hh) %>%
  mutate(totveh_duplex_Cpoly = tothh_duplex_Cpoly*avgveh_hh) %>%
  mutate(totveh_3to4_Cpoly = tothh_3to4_Cpoly*avgveh_hh) %>%
  mutate(totveh_5to9_Cpoly = tothh_5to9_Cpoly*avgveh_hh) %>%
  mutate(totveh_10to19_Cpoly = tothh_10to19_Cpoly*avgveh_hh) %>%
  mutate(totveh_20to49_Cpoly = tothh_20to49_Cpoly*avgveh_hh) %>%
  mutate(totveh_50plus_Cpoly = tothh_50plus_Cpoly*avgveh_hh) %>%
  mutate(vehwacc_Cpoly = value*totveh_Cpoly) %>%    # households per Cpoly, not percent
  mutate(vehwacc_SU_Cpoly = value*totveh_SU_Cpoly) %>% 
  mutate(vehwacc_duplex_Cpoly = value*totveh_duplex_Cpoly) %>% 
  mutate(vehwacc_3to4_Cpoly = value*totveh_3to4_Cpoly) %>% 
  mutate(vehwacc_5to9_Cpoly = value*totveh_5to9_Cpoly) %>% 
  mutate(vehwacc_10to19_Cpoly = value*totveh_10to19_Cpoly) %>% 
  mutate(vehwacc_20to49_Cpoly = value*totveh_20to49_Cpoly) %>% 
  mutate(vehwacc_50plus_Cpoly = value*totveh_50plus_Cpoly)%>%
  group_by(IOU, GEOID, variable) %>%
  summarise(avgacc_bg_pct = mean(value, na.rm=TRUE),# avg percent access in bg
            totveh_bg = sum(totveh_Cpoly, na.rm=TRUE), # total number of vehicules in block group
            totveh_SU_bg = sum(totveh_SU_Cpoly, na.rm=TRUE),
            totveh_duplex_bg = sum(totveh_duplex_Cpoly, na.rm=TRUE),
            totveh_3to4_bg = sum(totveh_3to4_Cpoly, na.rm=TRUE),
            totveh_5to9_bg = sum(totveh_5to9_Cpoly, na.rm=TRUE),
            totveh_10to19_bg = sum(totveh_10to19_Cpoly, na.rm=TRUE),
            totveh_20to49_bg = sum(totveh_20to49_Cpoly, na.rm=TRUE),
            totveh_50plus_bg = sum(totveh_50plus_Cpoly, na.rm=TRUE),
            vehwacc_bg_pct = sum(vehwacc_Cpoly, na.rm=TRUE)/(sum(totveh_Cpoly, na.rm=TRUE)),
            vehwacc_SU_bg_pct = sum(vehwacc_SU_Cpoly, na.rm=TRUE)/(sum(totveh_SU_Cpoly, na.rm=TRUE)),
            vehwacc_duplex_bg_pct = sum(vehwacc_duplex_Cpoly, na.rm=TRUE)/(sum(totveh_duplex_Cpoly, na.rm=TRUE)),
            vehwacc_3to4_bg_pct = sum(vehwacc_3to4_Cpoly, na.rm=TRUE)/(sum(totveh_3to4_Cpoly, na.rm=TRUE)),
            vehwacc_5to9_bg_pct = sum(vehwacc_5to9_Cpoly, na.rm=TRUE)/(sum(totveh_5to9_Cpoly, na.rm=TRUE)),
            vehwacc_10to19_bg_pct = sum(vehwacc_10to19_Cpoly, na.rm=TRUE)/(sum(totveh_10to19_Cpoly, na.rm=TRUE)),
            vehwacc_20to49_bg_pct = sum(vehwacc_20to49_Cpoly, na.rm=TRUE)/(sum(totveh_20to49_Cpoly, na.rm=TRUE)),
            vehwacc_50plus_bg_pct = sum(vehwacc_50plus_Cpoly, na.rm=TRUE)/(sum(totveh_50plus_Cpoly, na.rm=TRUE))
            )%>%
  mutate(variable = as.character(variable),
         threshold = sapply(strsplit(variable, "_"), function(x) x[2]),
         threshold = factor(ifelse(threshold=="0",">0",threshold), levels=c(">0",at)),
         DER = factor(sapply(strsplit(variable, "_"), function(x) x[3]), levels=c("ICL")),
         avgacc_bg_pct = as.numeric(avgacc_bg_pct))

###Computing total number of households with access
IOU_vehwacc_grid <- IOU_ICAaccess_grid %>%
  mutate(vehwacc_bg = vehwacc_bg_pct*totveh_bg) %>%
  mutate(vehwacc_SU_bg = vehwacc_SU_bg_pct*totveh_SU_bg) %>%
  mutate(vehwacc_duplex_bg = vehwacc_duplex_bg_pct*totveh_duplex_bg) %>%
  mutate(vehwacc_3to4_bg = vehwacc_3to4_bg_pct*totveh_3to4_bg) %>%
  mutate(vehwacc_5to9_bg = vehwacc_5to9_bg_pct*totveh_5to9_bg) %>%
  mutate(vehwacc_10to19_bg = vehwacc_10to19_bg_pct*totveh_10to19_bg) %>%
  mutate(vehwacc_20to49_bg = vehwacc_20to49_bg_pct*totveh_20to49_bg) %>%
  mutate(vehwacc_50plus_bg = vehwacc_50plus_bg_pct*totveh_50plus_bg) %>%
  mutate(DER = recode(DER, 'ICL'="Load")) %>%
  group_by(IOU, DER, threshold) %>%
  summarise(totveh = sum(totveh_bg, na.rm=TRUE),
            avgacc_pct = mean(avgacc_bg_pct, na.rm=TRUE),
            vehwacc_pct = sum(vehwacc_bg, na.rm=TRUE)/sum(totveh_bg, na.rm=TRUE),
            vehwacc_SU_pct = sum(vehwacc_SU_bg, na.rm=TRUE)/sum(totveh_SU_bg, na.rm=TRUE),
            vehwacc_duplex_pct = sum(vehwacc_duplex_bg, na.rm=TRUE)/sum(totveh_duplex_bg, na.rm=TRUE),
            vehwacc_3to4_pct = sum(vehwacc_3to4_bg, na.rm=TRUE)/sum(totveh_3to4_bg, na.rm=TRUE),
            vehwacc_5to9_pct = sum(vehwacc_5to9_bg, na.rm=TRUE)/sum(totveh_5to9_bg, na.rm=TRUE),
            vehwacc_10to19_pct = sum(vehwacc_10to19_bg, na.rm=TRUE)/sum(totveh_10to19_bg, na.rm=TRUE),
            vehwacc_20to49_pct = sum(vehwacc_20to49_bg, na.rm=TRUE)/sum(totveh_20to49_bg, na.rm=TRUE),
            vehwacc_50plus_pct = sum(vehwacc_50plus_bg, na.rm=TRUE)/sum(totveh_50plus_bg, na.rm=TRUE)) %>%
  mutate(threshold = as.numeric(ifelse(as.character(threshold)==">0","0",as.character(threshold))))
```
Visualizing results...

```{r}
lf <- melt(IOU_vehwacc_grid, id=c("IOU", "DER", "threshold", "totveh", "avgacc_pct"))

lf <- lf %>%
  mutate(feature = recode(factor(variable, levels=c("vehwacc_pct","vehwacc_SU_pct","vehwacc_duplex_pct","vehwacc_3to4_pct","vehwacc_5to9_pct", "vehwacc_10to19_pct", "vehwacc_20to49_pct", "vehwacc_50plus_pct")), 
                          'vehwacc_pct'="All", 'vehwacc_SU_pct'="Single Unit", 'vehwacc_duplex_pct'="Duplex", 
                          'vehwacc_3to4_pct'="3-4 units", 'vehwacc_5to9_pct'="5-9 units", 'vehwacc_10to19_pct'="10-19 units", 'vehwacc_20to49_pct'="20-49 units", 'vehwacc_50plus_pct'="More than 50 units"))

a <- ggplot(filter(lf), aes(x=threshold)) + plotops
print(a)

# ggsave("figures/access/IOU_access_households_size.png", a, width=8, height=5.5)
```


```{r}
# For the box grid plot
bg <- IOU_ICAaccess_grid %>% 
  filter(!is.na(vehwacc_bg_pct)) %>% 
  ggplot(aes(y=vehwacc_bg_pct)) + plotops_bggrid
bg

# ggsave("figures/access/IOU_access_bg_ICL.png", bg, width=8.5, height=5.5)
#ggsave("figures/access/IOU_access_bg_ICL.pdf", bg, width=8.5, height=6)

# For the line and point grid plot
all <- IOU_vehwacc_grid %>% 
  ggplot(aes(x=threshold, y=vehwacc_pct)) + plotops_allgrid
all
# ggsave("figures/access/IOU_access_all_ICL.png", all, width=8.5, height=5.5)

# Combine the plots
# plot_grid(all, bg, labels=c('a','b'), label_size=12, rel_widths=c(0.25,0.75), rel_heights=c(1,1))

# ggsave("figures/access/IOU_access_comb_ICL.png", width=11.5, height=6)
#ggsave("figures/access/IOU_access_comb_ICL.pdf", width=11.5, height=6)
```

--------------------------------------------------------------------------------------------

COUNTY CALCULATIONS

--------------------------------------------------------------------------------------------

```{r} 
###Computing number of households with access per county
IOU_ICAaccess_grid_cty <- 
  rbind(select(PGE_ICAaccess, IOU, tothh_Cpoly, GEOID, county, intersect(starts_with("hhwacc_"), ends_with("_pct"))),
        select(SCE_ICAaccess, IOU, tothh_Cpoly, GEOID, county, intersect(starts_with("hhwacc_"), ends_with("_pct"))))

IOU_ICAaccess_grid_cty <- merge(IOU_ICAaccess_grid_cty, ACS_bg_vehicles_hh[, c("GEOID", "avgveh_hh")], 
                     by = "GEOID", all.x = TRUE) %>%
  select(-GEOID) %>%
  melt(id=c("IOU", "tothh_Cpoly", "avgveh_hh", "county")) %>%
  mutate(totveh_Cpoly = tothh_Cpoly*avgveh_hh) %>%
  mutate(vehwacc_Cpoly = value*totveh_Cpoly) %>%    # households per Cpoly, not percent
  group_by(IOU, county, variable) %>%
  summarise(avgacc_cty_pct = mean(value, na.rm=TRUE), # avg percent access in county
            totveh_cty = sum(totveh_Cpoly, na.rm=TRUE), # total number of households in county
            vehwacc_cty_pct = sum(vehwacc_Cpoly, na.rm=TRUE)/sum(totveh_Cpoly, na.rm=TRUE)) %>%
  mutate(variable = as.character(variable),
         threshold = sapply(strsplit(variable, "_"), function(x) x[2]),
         threshold = factor(ifelse(threshold=="0",">0",threshold), levels=c(">0",at)),
         DER = factor(sapply(strsplit(variable, "_"), function(x) x[3]), levels=c("ICL")),
         avgacc_cty_pct = as.numeric(avgacc_cty_pct))
```
```{r}
###Cleaning data to exclude counties with too few households (we consider counties with at least 100 households)
IOU_ICAaccess_grid_cty <- IOU_ICAaccess_grid_cty %>%
    filter(!(county == "Alpine"),
           !(county == "Fresno" & IOU == "SCE"),
           !(county == "Inyo" & IOU == "PGE"),
           !(county == "Mariposa" & IOU == "SCE"),
           !(county == "Mono" & IOU == "PGE"),
           !(county == "Tuolumne" & IOU == "SCE"),
           !(county == "Ventura" & IOU == "PGE"),
           !(county == "Imperial"),
           !(county == "Lassen"),
           !(county == "Madera"),
           !(county == "San Diego"),
           !(county == "Siskiyou"),
           !(county == "Trinity"))
```

```{r}
#Plotting acess results for 1.5 and 4.5kW threshold
plot <- IOU_ICAaccess_grid_cty  %>%
  filter(threshold %in% c("1.5", "4.5"))

plot <- dcast(plot, IOU + county + totveh_cty ~ threshold, 
                   value.var = "vehwacc_cty_pct") %>%
  group_by(IOU, county) %>%
  rename("Access_1.5" = '1.5', "Access_4.5" = '4.5') %>%
  arrange(IOU, Access_1.5) %>%
  ungroup()

plot <- plot %>%
  distinct(IOU, county, .keep_all = TRUE)

# Setting the levels of 'county' factor based on the order in 'plot'
plot$county <- factor(plot$county, levels = unique(plot$county))

plot$household_category <- cut(plot$totveh_cty,
                               breaks = c(-Inf, 10000, 100000, 1000000, Inf),
                               labels = c("<10", "10-100", "100-1'000", ">1'000"),
                               right = FALSE)

IOU_access_county_plot <- ggplot(plot) +
  geom_segment(aes(x = county, xend = county,
                   y = Access_1.5, yend = Access_4.5,
                   color = household_category), size = 1) +
  geom_crossbar(aes(x = county, y = Access_1.5, ymin = Access_1.5, ymax = Access_1.5),
                width = 0.6, color = "black", size = 0.3) +
  geom_crossbar(aes(x = county, y = Access_4.5, ymin = Access_4.5, ymax = Access_4.5),
                width = 0.6, color = "black", size = 0.4) +
  geom_col(aes(x = county, y = Access_4.5, fill = household_category), width = 0.6)  +
  facet_grid(~ IOU, scales = "free_x", space = "free_x") +
  labs(
    x = "County",
    y = "Proportion of households with access",
    color=expression("Households x10"^"3"),
    fill=expression("Households x10"^"3")
  ) + theme_light() +
  theme(axis.text.x = element_text(size = 9, angle = 45, hjust = 1),
        legend.margin=margin(), legend.text=element_text(size=10)) +
  scale_y_continuous(labels = scales::percent_format(scale = 100)) +
  scale_color_discrete_sequential(palette="Viridis", nmax=4, order=4:1) +
  scale_fill_discrete_sequential(palette="Viridis", nmax=4, order=4:1) +
  guides(shape=guide_legend(nrow=4,title.position="top"))

ggsave("figures/access/vehicles/IOU_access_county.png", IOU_access_county_plot,  width = 12, height = 6.5, units = "in")

print(IOU_access_county_plot)
```

Printing statistics values of households access to use in tables

```{r}
accgr1 <- as.data.frame(IOU_hhwacc_grid) %>%
  select(c("IOU","DER", "threshold", "hhwacc_pct")) %>%
  filter((threshold==0.0 & DER=="Load") | threshold==1.5 | threshold==4.5 | threshold==10.0) %>%
  mutate(DER = ifelse(DER=="Load", "ICL")) %>%
  mutate(DER = paste0(DER," ",threshold)) %>% select(-c("threshold")) %>%
  mutate(hhwacc_pct = round(hhwacc_pct*100, digits=0)) %>%
  mutate(variable="full_territory")

accgr1 <- dcast(accgr1, IOU+variable~DER, value.var="hhwacc_pct")

  IOU_accessbg_grid_stats <- IOU_ICAaccess_grid %>%
  filter(!is.na(hhwacc_bg_pct) & !is.na(threshold)) %>%
  group_by(IOU, threshold) %>%
  summarise(
    median = median(hhwacc_bg_pct, na.rm = TRUE),
    lower_quartile = quantile(hhwacc_bg_pct, 0.25, na.rm = TRUE),
    upper_quartile = quantile(hhwacc_bg_pct, 0.75, na.rm = TRUE),
    min = min(hhwacc_bg_pct, na.rm = TRUE),
    max = max(hhwacc_bg_pct, na.rm = TRUE),
    iqr = IQR(hhwacc_bg_pct, na.rm = TRUE),
    lower_whisker = quantile(hhwacc_bg_pct, 0.25, na.rm = TRUE) - 1.5 * IQR(hhwacc_bg_pct, na.rm = TRUE),
    upper_whisker = quantile(hhwacc_bg_pct, 0.75, na.rm = TRUE) + 1.5 * IQR(hhwacc_bg_pct, na.rm = TRUE),
    .groups = "drop" # This will prevent the result from being grouped
  ) %>%
  # Ensuring the whiskers don't go beyond the actual data points
  mutate(
    lower_whisker = pmax(lower_whisker, min, na.rm = TRUE),
    upper_whisker = pmin(upper_whisker, max, na.rm = TRUE)
  )


#accgr2 <- rbind(PGE_accessbg_grid, SCE_accessbg_grid) %>%
accgr2 <- IOU_accessbg_grid_stats %>%
  select(c("IOU","threshold", "median", "lower_quartile","upper_quartile")) %>%
  dplyr::rename("25th pctl"="lower_quartile", "75th pctl"="upper_quartile") %>%
  mutate(median = round(median*100, digits=0),
    `25th pctl` = round(`25th pctl` * 100, digits = 0),
    `75th pctl` = round(`75th pctl` * 100, digits = 0)) %>%
  filter(threshold=='>0' | threshold=='1.5' | threshold=='4.5' | threshold=='10.') 

accgr2 <- accgr2 %>%
  pivot_longer(
    cols = c(median, `25th pctl`, `75th pctl`),
    names_to = "variable",
    values_to = "value"
  ) %>% pivot_wider(
        names_from = threshold,
        values_from = value,
        names_prefix = "threshold_"
    ) %>%
    select(IOU, variable, `threshold_>0`, `threshold_1.5`, `threshold_4.5`, `threshold_10.`) %>%
    arrange(IOU, variable) %>%
  rename(
    `ICL 0` = `threshold_>0`,
    `ICL 1.5` = threshold_1.5,
    `ICL 4.5` = threshold_4.5,
    `ICL 10` = threshold_10.
  )

# accgr2 <- dcast(accgr2, IOU+variable~DER, value.var="value")

accgr <- rbind(accgr1, filter(accgr2, variable=="75th pctl"|variable=="median"|variable=="25th pctl"))

accgr
rm(accgr1,accgr2)
```

```{r}
acchouse <- as.data.frame(IOU_hhwacc_grid) %>%
  select(-c("DER", "tothh", "avgacc_pct")) %>%
  filter((threshold==0.0) | threshold==1.5 | threshold==4.5 | threshold==10.0) %>%
  mutate(across(contains("pct"), ~ round(. * 100, digits = 0))) %>%
  dplyr::rename("All"='hhwacc_pct', "Single Unit"='hhwacc_SU_pct', "Duplex"='hhwacc_duplex_pct', 
                          "3-4 units"='hhwacc_3to4_pct', "5-9 units"='hhwacc_5to9_pct', "10-19 units"='hhwacc_10to19_pct', "20-49 units"='hhwacc_20to49_pct', "More than 50 units"='hhwacc_50plus_pct')

acchouse
```

```{r}
acctothh <- IOU_ICAaccess_grid %>%
    group_by(IOU, DER, threshold) %>%
    summarise(tothh = sum(tothh_bg, na.rm=TRUE),
              tothh_SU = sum(tothh_SU_bg, na.rm=TRUE),
              tothh_duplex = sum(tothh_duplex_bg, na.rm=TRUE),
              tothh_3to4 = sum(tothh_3to4_bg, na.rm=TRUE),
              tothh_5to9 = sum(tothh_5to9_bg, na.rm=TRUE),
              tothh_10to19 = sum(tothh_10to19_bg, na.rm=TRUE),
              tothh_20to49 = sum(tothh_20to49_bg, na.rm=TRUE),
              tothh_50plus = sum(tothh_50plus_bg, na.rm=TRUE))%>%
              select(-c("threshold")) %>%
              slice(1)%>%
  dplyr::rename("All"='tothh', "Single Unit"='tothh_SU', "Duplex"='tothh_duplex', 
                          "3-4 units"='tothh_3to4', "5-9 units"='tothh_5to9', "10-19 units"='tothh_10to19', "20-49 units"='tothh_20to49', "More than 50 units"='tothh_50plus')

acctothh
```